# Generated by Django 5.2.3 on 2025-07-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitaexamen',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Examen de Visita', 'verbose_name_plural': 'Exámenes de Visita'},
        ),
        migrations.AlterUniqueTogether(
            name='visitaexamen',
            unique_together={('visita', 'examen')},
        ),
        migrations.AddField(
            model_name='visitaexamen',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del Examen'),
        ),
        migrations.AddField(
            model_name='visitaexamen',
            name='evaluador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Evaluador'),
        ),
        migrations.AddField(
            model_name='visitaexamen',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitaexamen',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='visitaexamen',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitaexamen',
            name='notas_examinador',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Examinador'),
        ),
        migrations.AddField(
            model_name='visitaexamen',
            name='tiempo_duracion',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo de Duración'),
        ),
        migrations.RemoveField(
            model_name='visitaexamen',
            name='resultado',
        ),
    ]
