# Generated by Django 5.2.3 on 2025-08-04 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_visitaexamen_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atenasresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
        migrations.AlterField(
            model_name='berlinresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
        migrations.AlterField(
            model_name='epworthresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
        migrations.AlterField(
            model_name='isiresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
        migrations.AlterField(
            model_name='pittsburghresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
        migrations.AlterField(
            model_name='stopbangresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
    ]
