# Generated by Django 5.0.6 on 2026-03-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_consentimientofirmaenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentimientofirmaenvio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
