# Generated by Django 5.2.3 on 2025-08-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_atenasresult_visita_examen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='estado_visita',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20, verbose_name='Estado de la Visita'),
        ),
    ]
