# Generated by Django 5.2.3 on 2025-08-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_add_estado_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='actividad_fisica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='cama_actividades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='causa_conocida',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='consume',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='consume_medicamento',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='duracion_siestas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='especificacion_causa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='hora_acostarse_fds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='hora_acostarse_laboral',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='hora_acostarse_vacaciones',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='hora_despertar_fds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='hora_despertar_laboral',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='hora_despertar_vacaciones',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='hora_intencion_dormir_fds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='hora_intencion_dormir_laboral',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='hora_intencion_dormir_vacaciones',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='numero_siestas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='periodo_siestas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='presenta_queja',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='realiza_siestas',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='rutina_dormir',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='siesta_frecuencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='siesta_reparadora',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='sintomas_diurnos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='sintomas_sueno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='sueno_reparador_fds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='sueno_reparador_laboral',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='sueno_reparador_vacaciones',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='tiempo_dormirse_fds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='tiempo_dormirse_laboral',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='tiempo_dormirse_vacaciones',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='tiempo_salir_cama_fds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='tiempo_salir_cama_laboral',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='tiempo_salir_cama_vacaciones',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='usa_pantallas',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
    ]
