# Generated by Django 5.2.3 on 2025-08-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_suenoanamnesisresult_actividad_fisica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pittsburghresult',
            name='duerme_acompanado',
            field=models.CharField(max_length=100),
        ),
    ]
