# Generated by Django 5.0.6 on 2026-03-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_consentimientofirmaenvio_id'),
        ('home', '0005_backfill_examen_categoria'),
    ]

    operations = [
    ]
