# Generated by Django 5.0.6 on 2026-03-27 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20260322_1606'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='email_paciente',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='estado',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], db_index=True, default='agendada', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalvisita',
            name='estado_visita',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], db_index=True, default='abierta', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalvisita',
            name='firmado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Firmado'),
        ),
        migrations.AlterField(
            model_name='historicalvisitaexamen',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado del Examen'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado_visita',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], db_index=True, default='abierta', max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='firmado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Firmado'),
        ),
        migrations.AlterField(
            model_name='visitaexamen',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado del Examen'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['disponibilidad', 'fecha_cita', 'estado'], name='cita_disp_fecha_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['paciente', 'estado_visita'], name='visita_pac_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['paciente', 'fecha'], name='visita_pac_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='visitaexamen',
            index=models.Index(fields=['visita', 'estado'], name='visitaexam_visita_estado_idx'),
        ),
    ]
