# Generated by Django 5.2.5 on 2025-09-09 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_adherenciaterapeuticaresult_aqdcuidadorresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteYesavageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaccion_vida', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('disminuir_actividades', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('vida_vacia', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('aburrido_frecuente', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('buen_animo', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('preocupacion', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('felicidad', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('frecuencia_desamparado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('quedarse_casa', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('problemas_memoria', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('maravilla_vivir', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('inutil', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('lleno_energia', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('sin_esperanza', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('otras_personas_mejor', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('puntaje_total', models.IntegerField(default=0)),
                ('interpretacion', models.CharField(blank=True, max_length=255, null=True)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
