# Generated by Django 3.2.6 on 2025-09-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_adherenciaterapeuticaresult_aqdcuidadorresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettyFerrelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agotamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('cambios_alimenticios', models.CharField(blank=True, max_length=255, null=True)),
                ('dolor', models.CharField(blank=True, max_length=255, null=True)),
                ('cambios_sueno', models.CharField(blank=True, max_length=255, null=True)),
                ('salud_fisica_general', models.CharField(blank=True, max_length=255, null=True)),
                ('facilidad_enfrentar', models.CharField(blank=True, max_length=255, null=True)),
                ('felicidad', models.CharField(blank=True, max_length=255, null=True)),
                ('control_vida', models.CharField(blank=True, max_length=255, null=True)),
                ('satisfaccion_vida', models.CharField(blank=True, max_length=255, null=True)),
                ('concentracion', models.CharField(blank=True, max_length=255, null=True)),
                ('utilidad_personal', models.CharField(blank=True, max_length=255, null=True)),
                ('angustia_diagnostico', models.CharField(blank=True, max_length=255, null=True)),
                ('angustia_tratamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('ansiedad', models.CharField(blank=True, max_length=255, null=True)),
                ('depresion', models.CharField(blank=True, max_length=255, null=True)),
                ('miedo_otra_enfermedad', models.CharField(blank=True, max_length=255, null=True)),
                ('miedo_retroceso', models.CharField(blank=True, max_length=255, null=True)),
                ('miedo_avance', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_psicologico', models.CharField(blank=True, max_length=255, null=True)),
                ('angustia_familiar', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_ayuda', models.CharField(blank=True, max_length=255, null=True)),
                ('relaciones_personales', models.CharField(blank=True, max_length=255, null=True)),
                ('vida_sexual', models.CharField(blank=True, max_length=255, null=True)),
                ('trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('actividades_hogar', models.CharField(blank=True, max_length=255, null=True)),
                ('aislamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('carga_economica', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_social', models.CharField(blank=True, max_length=255, null=True)),
                ('actividades_religiosas', models.CharField(blank=True, max_length=255, null=True)),
                ('actividades_espirituales_personales', models.CharField(blank=True, max_length=255, null=True)),
                ('incertidumbre_futuro', models.CharField(blank=True, max_length=255, null=True)),
                ('cambios_positivos', models.CharField(blank=True, max_length=255, null=True)),
                ('proposito_vida', models.CharField(blank=True, max_length=255, null=True)),
                ('esperanza', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_espiritual', models.CharField(blank=True, max_length=255, null=True)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bettyferrelresult_resultado', to='home.visitaexamen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
