# Generated by Django 5.2.5 on 2025-09-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_participanteyesavageresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawtonBrodyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=10)),
                ('usar_telefono', models.CharField(max_length=255)),
                ('hacer_compras', models.CharField(max_length=255)),
                ('preparar_comida', models.CharField(max_length=255)),
                ('cuidado_casa', models.CharField(max_length=255)),
                ('lavar_ropa', models.CharField(max_length=255)),
                ('uso_transporte', models.CharField(max_length=255)),
                ('medicacion', models.CharField(max_length=255)),
                ('manejo_dinero', models.CharField(max_length=255)),
                ('puntaje_total', models.IntegerField()),
                ('diagnostico', models.CharField(max_length=100)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
