# Generated by Django 5.2.5 on 2025-09-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_create_redlatspanishresult'),
    ]

    operations = [
    ]
