# Generated by Django 3.2.6 on 2025-09-12 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bettyferrelresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntajeCDRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdr_memoria', models.CharField(max_length=10)),
                ('cdr_orientacion', models.CharField(max_length=10)),
                ('cdr_juicio', models.CharField(max_length=10)),
                ('cdr_comunitarias', models.CharField(max_length=10)),
                ('cdr_pasatiempos', models.CharField(max_length=10)),
                ('cdr_cuidado', models.CharField(max_length=10)),
                ('cdr_global', models.CharField(max_length=10)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntajecdrresult_resultado', to='home.visitaexamen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
