# Generated by Django 5.0.6 on 2026-07-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ensure_consentimiento_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registro_medico',
            field=models.CharField(blank=True, help_text='Número de registro médico / tarjeta profesional del firmante.', max_length=50, null=True, verbose_name='Registro médico'),
        ),
    ]
