# Generated by Django 5.0.6 on 2026-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userprofile_registro_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='calculos_mentales',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para hacer cálculos mentales? (por ejemplo: sumar, restar, multiplicar, dividir).'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='comer_solo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para comer solo?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='comunicarse_con_gente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para comunicarse con la gente?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='contener_orina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para contener la orina?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='decisiones_y_adaptacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado al paciente menos flexible para tomar decisiones y sin poder adaptarse a cosas nuevas?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='deprimido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado al paciente más deprimido?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='egoismo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado al paciente más egoísta y que no presta atención a las necesidades de los demás?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='enojo_menos_paciencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado que el paciente se enoja por pequeñeces y pierde la paciencia con más facilidad?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='entender_conversacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para entender conversaciones?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='entender_lectura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para entender lo que lee?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='entender_pelicula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para entender una película?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='escribir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para escribir?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='falta_de_interes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado al paciente con falta de interés en cosas que antes le interesaban?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='firmar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para firmar?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='hacer_tareas_hogar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para realizar tareas del hogar como cocinar, limpiar, etc.?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='llorar_con_facilidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado que el paciente llora con excesiva facilidad?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='manejar_dinero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para manejar dinero?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='mantener_orden',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para mantener en orden sus cosas?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='orientacion_en_casa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para orientarse dentro de su casa?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='orientacion_lugares_nuevos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para orientarse en lugares nuevos?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='orientacion_zona_donde_vive',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para orientarse en la zona donde vive?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='pasatiempos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para practicar sus pasatiempos?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='realizar_tramites',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para realizar trámites? (por ejemplo: ir al banco, a la EPS, etc.).'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='recordar_citas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para recordar citas (ejemplo: cuándo ir al médico)?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='recordar_compras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para recordar las cosas que va a comprar?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='recordar_fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para recordar la fecha?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='recordar_llamadas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para recordar llamadas telefónicas?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='recordar_lugar_objetos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene el paciente dificultades para recordar dónde deja los objetos en su casa?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='reir_situaciones_inapropiadas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado que el paciente se ríe en situaciones inapropiadas?'),
        ),
        migrations.AlterField(
            model_name='aqdcuidadorresult',
            name='temas_sexuales',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado al paciente más interesado en temas sexuales, y habla permanentemente de esos temas?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='calculos_mentales',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para hacer cálculos mentales? (por ejemplo: sumar, restar, multiplicar, dividir).'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='comer_solo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para comer solo?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='comunicarse_con_gente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para comunicarse con las personas?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='contener_orina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para contener la orina?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='decisiones_y_adaptacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Se siente usted menos flexible para tomar decisiones y sin poder adaptarse a cosas nuevas?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='deprimido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Se ha sentido más deprimido?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='egoismo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado que usted está más egoísta y no presta atención a las necesidades de los demás?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='enojo_menos_paciencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado que usted se enoja por pequeñeces y pierde la paciencia con más facilidad?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='entender_conversacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para entender conversaciones?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='entender_lectura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para entender lo que lee?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='entender_pelicula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para entender una película?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='escribir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para escribir?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='falta_de_interes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado usted falta de interés en cosas que antes le interesaban?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='firmar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para firmar?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='hacer_tareas_hogar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para realizar tareas del hogar como cocinar, limpiar, etc.?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='llorar_con_facilidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado usted que llora con excesiva facilidad?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='manejar_dinero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para manejar dinero?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='mantener_orden',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para mantener en orden sus cosas?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='orientacion_en_casa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para orientarse dentro de su casa?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='orientacion_lugares_nuevos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para orientarse en lugares nuevos?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='orientacion_zona_donde_vive',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para orientarse en la zona donde vive?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='pasatiempos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para practicar sus pasatiempos?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='realizar_tramites',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para realizar trámites? (por ejemplo: ir al banco, a la EPS, etc.).'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='recordar_citas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para recordar citas (ejemplo: cuándo ir al médico)?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='recordar_compras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para recordar las cosas que va a comprar?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='recordar_fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para recordar la fecha?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='recordar_llamadas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para recordar llamadas telefónicas?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='recordar_lugar_objetos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Tiene usted dificultades para recordar dónde deja los objetos en su casa?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='reir_situaciones_inapropiadas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado usted que se ríe en situaciones inapropiadas?'),
        ),
        migrations.AlterField(
            model_name='aqdparticipanteresult',
            name='temas_sexuales',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Ha notado que usted está más interesado en temas sexuales, y habla permanentemente de esos temas?'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='agitacion',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Agitación/Agresión'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='alucinaciones',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Alucinaciones'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='ansiedad',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Ansiedad'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='apatia',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Apatía/Indiferencia'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='apetito',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Apetito/Alimentación'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='conducta_motor',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Conducta Motora Aberrante'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='depresion',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Depresión/Disforia'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='desinhibicion',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Desinhibición'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='euforia',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Euforia/Alegría'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='ideas_delirantes',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Ideas delirantes'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='irritabilidad',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Irritabilidad/Labilidad'),
        ),
        migrations.AlterField(
            model_name='cuidadornpiresult',
            name='sueno',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('ns', 'No Sabe')], max_length=5, null=True, verbose_name='Sueño'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='alerta_manana',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Qué tan alerta te sientes durante la primera media hora después de despertarte por la mañana?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='apetito_manana',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Una vez levantado por las mañanas, ¿cómo es tu apetito durante la primera media hora?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='cansancio_11pm',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Si te fueras a la cama a las 11:00 p.m., ¿qué tan cansado estarías?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='descanso_manana',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Durante la primera media hora después de despertarte por la mañana, ¿qué tan cansado te sientes?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='despertar_tarde',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Te has acostado varias horas más tarde de lo habitual y al día siguiente no debes levantarte a ninguna hora en particular. ¿Cuándo crees que te despertarías?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='ejercicio_fisico',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ejercicio físico (MEQ)'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='ejercicio_manana',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ejercicio entre las 7:00 y las 8:00 a. m. (según tu reloj interno), ¿cómo crees que te desempeñarías?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='ejercicio_nocturno',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ejercicio físico intenso una hora dos veces por semana de 10 a 11 de la noche. Pensando en cuándo te sentirías mejor, ¿cómo crees que te sentaría?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='facilidad_levantarse',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Qué tan fácil te resulta levantarte por la mañana (cuando no te despiertan inesperadamente)?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='guardia_nocturna',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Una noche tienes que permanecer despierto de 4 a 6 de la madrugada por una guardia nocturna. Sin compromisos al día siguiente, ¿qué preferirías?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='hora_acostarse',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿A qué hora te irías a dormir si tuvieras total libertad para planificar tu noche?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='hora_acostarse_libre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Si no tuvieras compromisos al día siguiente, ¿a qué hora te irías a dormir en comparación con tu hora habitual?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='hora_cansancio_noche',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿A qué hora aproximada de la noche te sientes cansado y como consecuencia necesitas dormir?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='hora_despertarse_si_tarde',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Hora de despertar si te acuestas tarde (MEQ)'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='hora_levantarse',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿A qué hora te levantarías si tuvieras total libertad para planificar tu día?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='horario_trabajo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Jornada de cinco horas al día interesante y remunerada según tu rendimiento. ¿Qué cinco horas consecutivas seleccionarías?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='horario_trabajo_fisico',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Horario para trabajo físico (MEQ)'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='maximo_bienestar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿A qué hora del día crees que alcanzas tu máximo bienestar?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='nivel_cansancia_11',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nivel de cansancio (MEQ)'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='prueba_mental',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Para una prueba de dos horas mentalmente agotadora, siendo libre de planificar el día, ¿qué horario elegirías?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='puntuacion',
            field=models.IntegerField(verbose_name='Puntuación total MEQ'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='tipo_persona',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Se habla de personas de tipo matutino y vespertino. ¿Cuál de estos tipos te consideras ser?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='trabajo_fisico',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tienes que hacer dos horas de trabajo físico pesado y eres libre de planificar el día. Pensando en cuándo te sentirías mejor, ¿qué horario escogerías?'),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='uso_despertador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Si hay una hora específica a la que tienes que levantarte por la mañana, ¿en qué medida dependes de que te despierte un despertador?'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='alteracion_craneo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alteración cráneo o cara'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='amigdalas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hipertrofia de amígdalas (Escala de Friedman)'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='biotipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Biotipo'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='circunferencia_cuello',
            field=models.FloatField(blank=True, null=True, verbose_name='Circunferencia de cuello (cm)'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='desviacion_septo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Presencia de desviación de septo'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='grado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grado de obstrucción'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='hipertrofia_cornetes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hipertrofia de cornetes'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='hipertrofia_uvula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hipertrofia de úvula'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='imc',
            field=models.FloatField(blank=True, null=True, verbose_name='Índice de Masa Corporal (IMC)'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='mallampati',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clasificación de Mallampati'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='perimetro_abdominal',
            field=models.FloatField(blank=True, null=True, verbose_name='Perímetro abdominal (cm)'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (Kg)'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='rango_imc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rango IMC'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='simetria_narinas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Simetría de las narinas'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='talla',
            field=models.FloatField(blank=True, null=True, verbose_name='Talla (cm)'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='tipo_mordida',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de mordida'),
        ),
        migrations.AlterField(
            model_name='suenofisicoresult',
            name='tipo_narina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de narina'),
        ),
    ]
