# Generated by Django 3.2.6 on 2025-09-12 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_puntajecdrresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoInformadoParticipanteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('investigador', models.CharField(max_length=255)),
                ('version_consentimiento', models.CharField(max_length=50)),
                ('descripcion_proceso', models.TextField(blank=True, null=True)),
                ('preguntas', models.TextField(blank=True, null=True)),
                ('acepta', models.CharField(max_length=10)),
                ('hora_firma', models.TimeField()),
                ('fecha_firma', models.DateField()),
                ('testigo1', models.CharField(blank=True, max_length=255, null=True)),
                ('testigo2', models.CharField(blank=True, max_length=255, null=True)),
                ('copia_entregada', models.CharField(max_length=10)),
                ('hora_finalizacion', models.TimeField()),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientoinformadoparticipanteresult_resultado', to='home.visitaexamen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
