# Generated by Django 5.0.6 on 2026-07-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_aqdcuidadorresult_calculos_mentales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='actividades_fuera_hogar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Es él/ella capaz de llevar a cabo actividades fuera del hogar en forma independiente?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='actividades_no_realiza_en_hogar',
            field=models.TextField(blank=True, null=True, verbose_name='Si el sujeto se encuentra en un hogar geriátrico, ¿qué cosas ya no puede realizar bien (actividades domésticas y pasatiempos)?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='asiste_funciones_sociales',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='¿Asiste él/ella a funciones sociales fuera del hogar familiar?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cambios_pasatiempos',
            field=models.TextField(blank=True, null=True, verbose_name='¿Qué cambios se han registrado en las habilidades de él/ella para realizar pasatiempos?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cambios_tareas_domesticas',
            field=models.TextField(blank=True, null=True, verbose_name='¿Qué cambios se han registrado en las habilidades de él/ella para realizar tareas domésticas?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='colegio_grado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Último colegio al que asistió — Grado'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='colegio_lugar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Último colegio al que asistió — Lugar'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='colegio_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Último colegio al que asistió — Nombre'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='compras_independientes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Es él/ella todavía capaz de salir a comprar lo que necesita en forma independiente?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='conduce_actualmente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Actualmente, él/ella conduce un carro?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='condujo_alguna_vez',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Condujo él/ella alguna vez un carro?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cosas_que_aun_realiza_domesticas',
            field=models.TextField(blank=True, null=True, verbose_name='¿Qué cosas puede él/ella todavía realizar bien? (tareas domésticas)'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cosas_que_aun_realiza_pasatiempos',
            field=models.TextField(blank=True, null=True, verbose_name='¿Qué cosas puede él/ella todavía realizar bien? (pasatiempos)'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cuidado_p1',
            field=models.TextField(blank=True, null=True, verbose_name='Vestirse (The Dementia Scale of Blessed)'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cuidado_p2',
            field=models.TextField(blank=True, null=True, verbose_name='Lavado, aseo'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cuidado_p3',
            field=models.TextField(blank=True, null=True, verbose_name='Hábitos de alimentación'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cuidado_p4',
            field=models.TextField(blank=True, null=True, verbose_name='Control de esfínteres (The Dementia Scale of Blessed)'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='dejo_de_conducir_por_memoria',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='¿Se debe esto a problemas con su memoria o pensamiento?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='descripcion_habilidad_domestica',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la habilidad doméstica'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='dificultades_trabajo_memoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Él/Ella presenta dificultades significativas en el trabajo debido a problemas con su memoria o pensamiento?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='evento_recuerda_mes',
            field=models.TextField(blank=True, null=True, verbose_name='Evento reciente que debería recordar (en el curso de un mes)'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='evento_recuerda_semana',
            field=models.TextField(blank=True, null=True, verbose_name='Evento reciente que debería recordar (en el curso de una semana)'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='habilidad_domestica_dementia_scale',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidad para realizar tareas domésticas (Dementia Scale of Blessed)'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='info_suficiente_comunitarias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Existe suficiente información disponible para evaluar el grado de deterioro del sujeto en las actividades comunitarias?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='jubilacion',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuándo se jubiló él/ella (o cónyuge) y por qué?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='juicio_p1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='En general, si Ud. tuviera que evaluar la capacidad de él/ella para resolver problemas en este momento, Ud. la consideraría:'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='juicio_p2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Evalúe la capacidad de él/ella para manejar pequeñas sumas de dinero (ej. dar cambio, dejar una pequeña propina):'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='juicio_p3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Evalúe la capacidad de él/ella para manejar transacciones financieras o de negocios complicadas (ej. balancear una chequera, pagar cuentas):'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='juicio_p4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Puede él/ella manejar una emergencia doméstica (ej. gotera en las cañerías, pequeño incendio)?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='juicio_p5',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='¿Puede él/ella comprender situaciones o explicaciones?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='juicio_p6',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='¿Se comporta apropiadamente en situaciones sociales e interacciones con otra gente (como usualmente se comportaba antes de la enfermedad)?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_causa_jubilacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Problemas con la memoria o el pensamiento de él/ella contribuyeron a su decisión de jubilarse?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Ha notado pérdida de memoria reciente?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p1_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='¿Es este un problema constante (a diferencia de esporádico)?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='¿Puede él/ella recordar eventos recientes?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Puede él/ella recordar una lista breve de artículos (compras)?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Se ha registrado algún deterioro en su memoria durante el último año?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Se encuentra su memoria deteriorada a tal punto que habría interferido con la realización de sus actividades cotidianas habituales de años atrás (o actividades previas a la jubilación)?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Se olvida él/ella completamente de un evento importante (ej., viaje, fiesta, matrimonio familiar) a pocas semanas del evento?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p7',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Se olvida él/ella de detalles relevantes del evento importante?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p8',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Se olvida él/ella completamente de información importante del pasado lejano (ej. fecha de cumpleaños, fecha de matrimonio, lugar de trabajo)?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='motivo_no_funciones',
            field=models.TextField(blank=True, null=True, verbose_name='En caso negativo, ¿por qué no asiste a funciones sociales?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='nacimiento_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='¿Cuándo nació él/ella?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='nacimiento_lugar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Dónde nació él/ella?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='nivel_desempeno_domestico',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='¿En qué nivel es él/ella capaz de realizar tareas domésticas?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='notas_comunitarias',
            field=models.TextField(blank=True, null=True, verbose_name='Notas adicionales (actividades comunitarias)'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='ocupacion_principal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Cuál fue la principal ocupación de él/ella (o la ocupación del cónyuge si el sujeto no trabajaba)?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Con qué frecuencia sabe él/ella exactamente la fecha del día?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Con qué frecuencia sabe él/ella exactamente el mes?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Con qué frecuencia sabe él/ella exactamente el año?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Con qué frecuencia sabe él/ella exactamente el día de la semana?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Presenta él/ella dificultad para relacionar acontecimientos en el tiempo (cuándo ocurrieron unos eventos en relación con los otros)?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Puede él/ella orientarse en calles que le son conocidas?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p7',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Con qué frecuencia sabe él/ella cómo llegar de un lugar a otro cuando se encuentra fuera de su vecindario?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p8',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Con qué frecuencia puede él/ella orientarse dentro de su casa?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='parece_enfermo',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='¿Alguien que no conozca al sujeto y observara su comportamiento pensaría que éste/a se encuentra enfermo/a?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='participa_hogar_geriatrico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Si el sujeto se encuentra en un hogar geriátrico, ¿participa activamente él/ella en actividades sociales (con participación intelectual)?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='riesgos_conduccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Si él/ella todavía conduce, ¿existen problemas o riesgos debido a un pensamiento pobre?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='trabaja_actualmente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Él/Ella sigue trabajando?'),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='ultimo_trabajo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Cuál fue el último trabajo de él/ella (o trabajo del cónyuge si el sujeto no trabajaba)?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='colegio_grado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Último colegio al que asistió — Grado'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='colegio_lugar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Último colegio al que asistió — Lugar'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='colegio_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Último colegio al que asistió — Nombre'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo1_avenida',
            field=models.BooleanField(default=False, verbose_name='Ensayo 1 — Avenida Boyacá'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo1_cali',
            field=models.BooleanField(default=False, verbose_name='Ensayo 1 — Cali'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo1_calle',
            field=models.BooleanField(default=False, verbose_name='Ensayo 1 — Calle 42'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo1_juan',
            field=models.BooleanField(default=False, verbose_name='Ensayo 1 — Juan'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo1_perez',
            field=models.BooleanField(default=False, verbose_name='Ensayo 1 — Pérez'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo2_avenida',
            field=models.BooleanField(default=False, verbose_name='Ensayo 2 — Avenida Boyacá'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo2_cali',
            field=models.BooleanField(default=False, verbose_name='Ensayo 2 — Cali'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo2_calle',
            field=models.BooleanField(default=False, verbose_name='Ensayo 2 — Calle 42'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo2_juan',
            field=models.BooleanField(default=False, verbose_name='Ensayo 2 — Juan'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo2_perez',
            field=models.BooleanField(default=False, verbose_name='Ensayo 2 — Pérez'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo3_avenida',
            field=models.BooleanField(default=False, verbose_name='Ensayo 3 — Avenida Boyacá'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo3_cali',
            field=models.BooleanField(default=False, verbose_name='Ensayo 3 — Cali'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo3_calle',
            field=models.BooleanField(default=False, verbose_name='Ensayo 3 — Calle 42'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo3_juan',
            field=models.BooleanField(default=False, verbose_name='Ensayo 3 — Juan'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ensayo3_perez',
            field=models.BooleanField(default=False, verbose_name='Ensayo 3 — Pérez'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='evento_recuerda_mes',
            field=models.TextField(blank=True, null=True, verbose_name='Evento reciente que debería recordar (en el curso de un mes)'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='evento_recuerda_semana',
            field=models.TextField(blank=True, null=True, verbose_name='Evento reciente que debería recordar (en el curso de una semana)'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='¿Cuándo nació?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='jubilacion',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuándo se jubiló (o su cónyuge) y por qué?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p1_puntaje',
            field=models.IntegerField(blank=True, null=True, verbose_name='¿En qué se parecen un rábano y una coliflor? — Puntaje'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p1_respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='¿En qué se parecen un rábano y una coliflor? — Respuesta'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p2_puntaje',
            field=models.IntegerField(blank=True, null=True, verbose_name='¿En qué se parecen un escritorio y una estantería? — Puntaje'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p2_respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='¿En qué se parecen un escritorio y una estantería? — Respuesta'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p3_puntaje',
            field=models.IntegerField(blank=True, null=True, verbose_name='¿Cuál es la diferencia entre una mentira y una equivocación? — Puntaje'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p3_respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuál es la diferencia entre una mentira y una equivocación? — Respuesta'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p4_puntaje',
            field=models.IntegerField(blank=True, null=True, verbose_name='¿Cuál es la diferencia entre un río y un canal? — Puntaje'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p4_respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuál es la diferencia entre un río y un canal? — Respuesta'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p5',
            field=models.CharField(blank=True, choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], max_length=15, null=True, verbose_name='¿Cuántos centavos hay en un peso?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p6',
            field=models.CharField(blank=True, choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], max_length=15, null=True, verbose_name='¿Cuántas monedas de 50 pesos hay en $1,350?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p7',
            field=models.CharField(blank=True, choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], max_length=15, null=True, verbose_name='Restar 3 de 20 y continuar hasta llegar a 2 o 1'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p8_puntaje',
            field=models.IntegerField(blank=True, null=True, verbose_name='Al llegar a una ciudad extraña, ¿cómo localizaría usted a un amigo? — Puntaje'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='juicio_p9',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Evaluación del sujeto respecto a su discapacidad, posición social y comprensión de por qué se encuentra en el test'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Dónde nació?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='memoria_mes_calificacion',
            field=models.TextField(blank=True, null=True, verbose_name='Calificación del recuerdo (mes)'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='memoria_p1',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='¿Tiene usted problemas con su memoria o pensamiento?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='memoria_semana_calificacion',
            field=models.TextField(blank=True, null=True, verbose_name='Calificación del recuerdo (semana)'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ocupacion_principal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Cuál era su principal ocupación/trabajo o la de su cónyuge, si Ud. no estaba empleado/a?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='¿Qué fecha es hoy?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Qué día de la semana es hoy?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿En qué mes estamos?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿En qué año estamos?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p5',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='¿Cómo se llama este lugar?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p6',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='¿En qué pueblo o ciudad estamos?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p7',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Qué hora es?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p8',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Sabe el sujeto quién es el informante (según el criterio del entrevistador)?'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='repeticion_avenida',
            field=models.BooleanField(default=False, verbose_name='Repetición — Avenida Boyacá'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='repeticion_cali',
            field=models.BooleanField(default=False, verbose_name='Repetición — Cali'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='repeticion_calle',
            field=models.BooleanField(default=False, verbose_name='Repetición — Calle 42'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='repeticion_juan',
            field=models.BooleanField(default=False, verbose_name='Repetición — Juan'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='repeticion_perez',
            field=models.BooleanField(default=False, verbose_name='Repetición — Pérez'),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='ultimo_trabajo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Cuál fue su último trabajo importante (o el de su cónyuge, si Ud. no estaba empleado/a)?'),
        ),
    ]
