# Generated by Django 3.2.6 on 2025-09-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_consentimientoinformadoparticipanteresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoInformadoCuidadorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('investigador', models.CharField(max_length=255)),
                ('nombre_acompanante', models.CharField(max_length=255)),
                ('nombre_participante', models.CharField(max_length=255)),
                ('version_consentimiento', models.CharField(max_length=50)),
                ('descripcion_proceso', models.TextField(blank=True, null=True)),
                ('preguntas', models.TextField(blank=True, null=True)),
                ('acepta', models.CharField(max_length=10)),
                ('hora_firma', models.TimeField()),
                ('fecha_firma', models.DateField()),
                ('testigo1', models.CharField(blank=True, max_length=255, null=True)),
                ('testigo2', models.CharField(blank=True, max_length=255, null=True)),
                ('copia_entregada', models.CharField(max_length=10)),
                ('hora_finalizacion', models.TimeField()),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientoinformadocuidadorresult_resultado', to='home.visitaexamen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnamnesisParticipanteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=100)),
                ('lugar_nacimiento', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('tiempo_acompanando', models.CharField(max_length=100)),
                ('ingresos_hogar', models.CharField(max_length=50)),
                ('estrato', models.CharField(max_length=20)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('lateralidad', models.CharField(blank=True, max_length=50, null=True)),
                ('convivencia', models.TextField(blank=True, null=True)),
                ('eps', models.CharField(blank=True, max_length=100, null=True)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesisparticipanteresult_resultado', to='home.visitaexamen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnamnesisCuidadorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=100)),
                ('lugar_nacimiento', models.CharField(max_length=255)),
                ('lugar_procedencia', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=50)),
                ('relacion', models.CharField(max_length=100)),
                ('tiempo_acompanando', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(blank=True, max_length=255, null=True)),
                ('escolaridad', models.CharField(blank=True, max_length=100, null=True)),
                ('ingresos_hogar', models.CharField(max_length=50)),
                ('estrato', models.CharField(max_length=20)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('lateralidad', models.CharField(blank=True, max_length=50, null=True)),
                ('convivencia', models.TextField(blank=True, null=True)),
                ('eps', models.CharField(blank=True, max_length=100, null=True)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesiscuidadorresult_resultado', to='home.visitaexamen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
