# Generated by Django 3.2.6 on 2025-09-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_anamnesiscuidadorresult_anamnesisparticipanteresult_consentimientoinformadocuidadorresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berlinresult',
            name='presion_alta',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berlinresult',
            name='somnolencia_conducir',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
