# Generated by Django 5.0.6 on 2026-07-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_cdr_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqdcuidadorresult',
            name='puntaje_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Puntaje total'),
        ),
        migrations.AddField(
            model_name='aqdparticipanteresult',
            name='puntaje_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Puntaje total'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='seccion_abdomen_evaluado',
            field=models.BooleanField(default=True, verbose_name='Abdomen evaluado'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='seccion_cabeza_cuello_evaluado',
            field=models.BooleanField(default=True, verbose_name='Cabeza y cuello evaluados'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='seccion_osteomuscular_evaluado',
            field=models.BooleanField(default=True, verbose_name='Osteomuscular evaluado'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='seccion_piel_evaluado',
            field=models.BooleanField(default=True, verbose_name='Piel y anexos evaluados'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='seccion_signos_vitales_evaluado',
            field=models.BooleanField(default=True, verbose_name='Signos vitales evaluados'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='seccion_torax_evaluado',
            field=models.BooleanField(default=True, verbose_name='Tórax/Cardio/Resp evaluado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='seccion_coordinacion_marcha_evaluado',
            field=models.BooleanField(default=True, verbose_name='Coordinación / marcha / movimientos evaluados'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='seccion_fuerza_evaluado',
            field=models.BooleanField(default=True, verbose_name='Fuerza muscular evaluada'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='seccion_pares_craneales_evaluado',
            field=models.BooleanField(default=True, verbose_name='Pares craneales evaluados'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='seccion_reflejos_evaluado',
            field=models.BooleanField(default=True, verbose_name='Reflejos evaluados'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='seccion_sensibilidad_evaluado',
            field=models.BooleanField(default=True, verbose_name='Sensibilidad evaluada'),
        ),
        migrations.AddField(
            model_name='puntajecdrresult',
            name='suma_cajas',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Suma de cajas'),
        ),
        migrations.AddField(
            model_name='redlatspanishresult',
            name='puntaje_total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Puntaje total'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='arcos_movimiento_inferiores_normal',
            field=models.BooleanField(default=True, verbose_name='Arcos Movimiento Inferiores Normal'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='arcos_movimiento_superiores_normal',
            field=models.BooleanField(default=True, verbose_name='Arcos Movimiento Superiores Normal'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='asimetrias_inferiores_normal',
            field=models.BooleanField(default=True, verbose_name='Asimetrías Inferiores Normal'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='asimetrias_superiores_normal',
            field=models.BooleanField(default=True, verbose_name='Asimetrías Superiores Normal'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='cuello_normal',
            field=models.BooleanField(default=True, verbose_name='Cuello Normal'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='cuero_cabelludo_normal',
            field=models.BooleanField(default=True, verbose_name='Cuero Cabelludo Normal'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='curvatura_cervical_normal',
            field=models.BooleanField(default=True, verbose_name='Curvatura Cervical Normal'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='curvatura_lumbar_normal',
            field=models.BooleanField(default=True, verbose_name='Curvatura Lumbar Normal'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='curvatura_toracica_normal',
            field=models.BooleanField(default=True, verbose_name='Curvatura Torácica Normal'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='nariz_normal',
            field=models.BooleanField(default=True, verbose_name='Nariz Normal'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='oidos_normal',
            field=models.BooleanField(default=True, verbose_name='Oídos Normal'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='pared_abdominal_normal',
            field=models.BooleanField(default=True, verbose_name='Pared Abdominal Normal'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='alcohol_derecho',
            field=models.BooleanField(default=True, verbose_name='Alcohol - Fosa nasal derecha'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='alcohol_izquierdo',
            field=models.BooleanField(default=True, verbose_name='Alcohol - Fosa nasal izquierda'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='cafe_derecho',
            field=models.BooleanField(default=True, verbose_name='Café - Fosa nasal derecha'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='cafe_izquierdo',
            field=models.BooleanField(default=True, verbose_name='Café - Fosa nasal izquierda'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='canela_derecho',
            field=models.BooleanField(default=True, verbose_name='Canela - Fosa nasal derecha'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='canela_izquierdo',
            field=models.BooleanField(default=True, verbose_name='Canela - Fosa nasal izquierda'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='clavos_derecho',
            field=models.BooleanField(default=True, verbose_name='Clavos - Fosa nasal derecha'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='clavos_izquierdo',
            field=models.BooleanField(default=True, verbose_name='Clavos - Fosa nasal izquierda'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='dolor_abdomen',
            field=models.BooleanField(default=True, verbose_name='Dolor al pinchazo - Abdomen alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='dolor_cuello',
            field=models.BooleanField(default=True, verbose_name='Dolor al pinchazo - Cuello alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='dolor_frente_globo',
            field=models.BooleanField(default=True, verbose_name='Dolor - Frente/globo ocular alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='dolor_labio_inf_menton',
            field=models.BooleanField(default=True, verbose_name='Dolor - Labio inferior/mentón alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='dolor_miembros_inferiores',
            field=models.BooleanField(default=True, verbose_name='Dolor al pinchazo - Miembros inferiores alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='dolor_miembros_superiores',
            field=models.BooleanField(default=True, verbose_name='Dolor al pinchazo - Miembros superiores alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='dolor_parpado_labio_sup',
            field=models.BooleanField(default=True, verbose_name='Dolor - Párpado inferior/labio superior alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='dolor_torax',
            field=models.BooleanField(default=True, verbose_name='Dolor al pinchazo - Tórax alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='fuerza_maseteros',
            field=models.BooleanField(default=True, verbose_name='Fuerza muscular - Maseteros alterada'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='fuerza_pterigoideos',
            field=models.BooleanField(default=True, verbose_name='Fuerza muscular - Pterigoideos alterada'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='fuerza_temporales',
            field=models.BooleanField(default=True, verbose_name='Fuerza muscular - Temporales alterada'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='mimica_buccinadores',
            field=models.BooleanField(default=True, verbose_name='Mímica facial - Buccinadores alterada'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='mimica_elevacion_nasal',
            field=models.BooleanField(default=True, verbose_name='Mímica facial - Elevación nasal alterada'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='mimica_frente',
            field=models.BooleanField(default=True, verbose_name='Mímica facial - Frente alterada'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='mimica_orbicular_labios',
            field=models.BooleanField(default=True, verbose_name='Mímica facial - Orbicular labios alterada'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='mimica_parpados',
            field=models.BooleanField(default=True, verbose_name='Mímica facial - Párpados alterada'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='pimienta_derecho',
            field=models.BooleanField(default=True, verbose_name='Pimienta - Fosa nasal derecha'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='pimienta_izquierdo',
            field=models.BooleanField(default=True, verbose_name='Pimienta - Fosa nasal izquierda'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='tactil_abdomen',
            field=models.BooleanField(default=True, verbose_name='Táctil superficial - Abdomen alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='tactil_cuello',
            field=models.BooleanField(default=True, verbose_name='Táctil superficial - Cuello alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='tactil_miembros_inferiores',
            field=models.BooleanField(default=True, verbose_name='Táctil superficial - Miembros inferiores alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='tactil_miembros_superiores',
            field=models.BooleanField(default=True, verbose_name='Táctil superficial - Miembros superiores alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='tactil_torax',
            field=models.BooleanField(default=True, verbose_name='Táctil superficial - Tórax alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='tacto_frente_globo',
            field=models.BooleanField(default=True, verbose_name='Tacto superficial - Frente/globo ocular alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='tacto_labio_inf_menton',
            field=models.BooleanField(default=True, verbose_name='Tacto superficial - Labio inferior/mentón alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='tacto_parpado_labio_sup',
            field=models.BooleanField(default=True, verbose_name='Tacto superficial - Párpado inferior/labio superior alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='temp_frente_globo',
            field=models.BooleanField(default=True, verbose_name='Temperatura - Frente/globo ocular alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='temp_labio_inf_menton',
            field=models.BooleanField(default=True, verbose_name='Temperatura - Labio inferior/mentón alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='temp_parpado_labio_sup',
            field=models.BooleanField(default=True, verbose_name='Temperatura - Párpado inferior/labio superior alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='termica_abdomen',
            field=models.BooleanField(default=True, verbose_name='Sensibilidad térmica - Abdomen alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='termica_cuello',
            field=models.BooleanField(default=True, verbose_name='Sensibilidad térmica - Cuello alterada'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='termica_miembros_inferiores',
            field=models.BooleanField(default=True, verbose_name='Sensibilidad térmica - Miembros inferiores alterada'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='termica_miembros_superiores',
            field=models.BooleanField(default=True, verbose_name='Sensibilidad térmica - Miembros superiores alterada'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='termica_torax',
            field=models.BooleanField(default=True, verbose_name='Sensibilidad térmica - Tórax alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='trofismo_maseteros',
            field=models.BooleanField(default=True, verbose_name='Trofismo - Maseteros alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='trofismo_pterigoideos',
            field=models.BooleanField(default=True, verbose_name='Trofismo - Pterigoideos alterado'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='trofismo_temporales',
            field=models.BooleanField(default=True, verbose_name='Trofismo - Temporales alterado'),
        ),
    ]
