# Generated by Django 5.0.6 on 2026-07-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_epic_b_toggles_evaluado_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='atenasresult',
            name='interpretacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Interpretación'),
        ),
        migrations.AddField(
            model_name='berlinresult',
            name='categoria1_positiva',
            field=models.BooleanField(blank=True, null=True, verbose_name='Categoría 1 positiva (ronquidos)'),
        ),
        migrations.AddField(
            model_name='berlinresult',
            name='categoria2_positiva',
            field=models.BooleanField(blank=True, null=True, verbose_name='Categoría 2 positiva (somnolencia)'),
        ),
        migrations.AddField(
            model_name='berlinresult',
            name='categoria3_positiva',
            field=models.BooleanField(blank=True, null=True, verbose_name='Categoría 3 positiva (HTA/IMC)'),
        ),
        migrations.AddField(
            model_name='berlinresult',
            name='categorias_positivas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nº de categorías positivas'),
        ),
        migrations.AddField(
            model_name='berlinresult',
            name='imc',
            field=models.FloatField(blank=True, null=True, verbose_name='IMC'),
        ),
        migrations.AddField(
            model_name='berlinresult',
            name='interpretacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Interpretación'),
        ),
        migrations.AddField(
            model_name='berlinresult',
            name='riesgo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nivel de riesgo'),
        ),
        migrations.AddField(
            model_name='bettyferrelresult',
            name='interpretacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Interpretación'),
        ),
        migrations.AddField(
            model_name='bettyferrelresult',
            name='promedio_espiritual',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio bienestar espiritual'),
        ),
        migrations.AddField(
            model_name='bettyferrelresult',
            name='promedio_fisico',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio bienestar físico'),
        ),
        migrations.AddField(
            model_name='bettyferrelresult',
            name='promedio_global',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio global'),
        ),
        migrations.AddField(
            model_name='bettyferrelresult',
            name='promedio_psicologico',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio bienestar psicológico'),
        ),
        migrations.AddField(
            model_name='bettyferrelresult',
            name='promedio_social',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio bienestar social'),
        ),
        migrations.AddField(
            model_name='epworthresult',
            name='interpretacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Interpretación'),
        ),
        migrations.AddField(
            model_name='euroqol5d5lresult',
            name='estado_salud',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Estado de salud (código EQ-5D)'),
        ),
        migrations.AddField(
            model_name='isiresult',
            name='interpretacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Interpretación'),
        ),
        migrations.AddField(
            model_name='mocaresult',
            name='mis',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='MIS (índice de memoria)'),
        ),
        migrations.AddField(
            model_name='mocaresult',
            name='pista_cat_clavel',
            field=models.BooleanField(default=False, verbose_name='Pista categoría: clavel'),
        ),
        migrations.AddField(
            model_name='mocaresult',
            name='pista_cat_iglesia',
            field=models.BooleanField(default=False, verbose_name='Pista categoría: iglesia'),
        ),
        migrations.AddField(
            model_name='mocaresult',
            name='pista_cat_rojo',
            field=models.BooleanField(default=False, verbose_name='Pista categoría: rojo'),
        ),
        migrations.AddField(
            model_name='mocaresult',
            name='pista_cat_rostro',
            field=models.BooleanField(default=False, verbose_name='Pista categoría: rostro'),
        ),
        migrations.AddField(
            model_name='mocaresult',
            name='pista_cat_seda',
            field=models.BooleanField(default=False, verbose_name='Pista categoría: seda'),
        ),
        migrations.AddField(
            model_name='mocaresult',
            name='pista_opcion_clavel',
            field=models.BooleanField(default=False, verbose_name='Pista opción: clavel'),
        ),
        migrations.AddField(
            model_name='mocaresult',
            name='pista_opcion_iglesia',
            field=models.BooleanField(default=False, verbose_name='Pista opción: iglesia'),
        ),
        migrations.AddField(
            model_name='mocaresult',
            name='pista_opcion_rojo',
            field=models.BooleanField(default=False, verbose_name='Pista opción: rojo'),
        ),
        migrations.AddField(
            model_name='mocaresult',
            name='pista_opcion_rostro',
            field=models.BooleanField(default=False, verbose_name='Pista opción: rostro'),
        ),
        migrations.AddField(
            model_name='mocaresult',
            name='pista_opcion_seda',
            field=models.BooleanField(default=False, verbose_name='Pista opción: seda'),
        ),
        migrations.AddField(
            model_name='pittsburghresult',
            name='componente_calidad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Componente 1: Calidad subjetiva'),
        ),
        migrations.AddField(
            model_name='pittsburghresult',
            name='componente_disfuncion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Componente 7: Disfunción diurna'),
        ),
        migrations.AddField(
            model_name='pittsburghresult',
            name='componente_duracion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Componente 3: Duración'),
        ),
        migrations.AddField(
            model_name='pittsburghresult',
            name='componente_eficiencia',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Componente 4: Eficiencia'),
        ),
        migrations.AddField(
            model_name='pittsburghresult',
            name='componente_latencia',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Componente 2: Latencia'),
        ),
        migrations.AddField(
            model_name='pittsburghresult',
            name='componente_medicacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Componente 6: Medicación'),
        ),
        migrations.AddField(
            model_name='pittsburghresult',
            name='componente_perturbaciones',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Componente 5: Perturbaciones'),
        ),
        migrations.AddField(
            model_name='pittsburghresult',
            name='interpretacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Interpretación'),
        ),
        migrations.AlterField(
            model_name='lawtonbrodyresult',
            name='diagnostico',
            field=models.CharField(max_length=100, verbose_name='Interpretación'),
        ),
        migrations.AlterField(
            model_name='puntajecdrresult',
            name='suma_cajas',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Suma de los 6 dominios (cajas)'),
        ),
    ]
