# Generated by Django 3.2.6 on 2025-09-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20250915_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisGeneralResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis_historia', models.TextField(blank=True, null=True, verbose_name='Análisis de Historia Clínica')),
                ('plan_tratamiento', models.TextField(blank=True, null=True, verbose_name='Plan de Tratamiento')),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisisgeneralresult_resultado', to='home.visitaexamen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoNoClasificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=500, verbose_name='Descripción del Diagnóstico No Clasificado')),
                ('confirmado_nuevo', models.BooleanField(default=False)),
                ('confirmado_antiguo', models.BooleanField(default=False)),
                ('en_estudio', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de aparición')),
                ('analisis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_no_clasificados', to='home.analisisgeneralresult')),
            ],
            options={
                'verbose_name': 'Diagnóstico No Clasificado',
                'verbose_name_plural': 'Diagnósticos No Clasificados',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoICSD3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código ICSD-3 (ej. G47.00)', max_length=20, verbose_name='Código ICSD-3')),
                ('diagnostico', models.CharField(max_length=500, verbose_name='Descripción del Diagnóstico')),
                ('confirmado_nuevo', models.BooleanField(default=False)),
                ('confirmado_antiguo', models.BooleanField(default=False)),
                ('en_estudio', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de aparición')),
                ('analisis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_icsd3', to='home.analisisgeneralresult')),
            ],
            options={
                'verbose_name': 'Diagnóstico ICSD-3',
                'verbose_name_plural': 'Diagnósticos ICSD-3',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoDSMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código DSM-V (ej. 296.2x)', max_length=20, verbose_name='Código DSM-V')),
                ('diagnostico', models.CharField(max_length=500, verbose_name='Descripción del Diagnóstico')),
                ('confirmado_nuevo', models.BooleanField(default=False)),
                ('confirmado_antiguo', models.BooleanField(default=False)),
                ('en_estudio', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de aparición')),
                ('analisis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_dsmv', to='home.analisisgeneralresult')),
            ],
            options={
                'verbose_name': 'Diagnóstico DSM-V',
                'verbose_name_plural': 'Diagnósticos DSM-V',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoCIE10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código CIE-10 (ej. F32.9)', max_length=20, verbose_name='Código CIE-10')),
                ('diagnostico', models.CharField(max_length=500, verbose_name='Descripción del Diagnóstico')),
                ('confirmado_nuevo', models.BooleanField(default=False)),
                ('confirmado_antiguo', models.BooleanField(default=False)),
                ('en_estudio', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de aparición')),
                ('analisis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_cie10', to='home.analisisgeneralresult')),
            ],
            options={
                'verbose_name': 'Diagnóstico CIE-10',
                'verbose_name_plural': 'Diagnósticos CIE-10',
                'ordering': ['orden'],
            },
        ),
    ]
