# Generated by Django 5.0.6 on 2026-09-05 22:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_epic_d_scores_interpretaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvisita',
            name='estado_visita',
            field=models.CharField(choices=[('programada', 'Programada'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado_visita',
            field=models.CharField(choices=[('programada', 'Programada'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalSerieVisitas',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('frecuencia_unidad', models.CharField(choices=[('dias', 'Días'), ('semanas', 'Semanas'), ('meses', 'Meses')], default='meses', max_length=10)),
                ('frecuencia_cada', models.PositiveIntegerField(default=1)),
                ('examenes', models.JSONField(blank=True, default=list, help_text='Snapshot de IDs de exámenes a materializar al abrir cada visita.', verbose_name='Exámenes del plan')),
                ('activa', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Tipo_visita', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.tipovisita')),
                ('evaluador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.datosdemograficos')),
            ],
            options={
                'verbose_name': 'historical Serie de visitas',
                'verbose_name_plural': 'historical Series de visitas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SerieVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('frecuencia_unidad', models.CharField(choices=[('dias', 'Días'), ('semanas', 'Semanas'), ('meses', 'Meses')], default='meses', max_length=10)),
                ('frecuencia_cada', models.PositiveIntegerField(default=1)),
                ('examenes', models.JSONField(blank=True, default=list, help_text='Snapshot de IDs de exámenes a materializar al abrir cada visita.', verbose_name='Exámenes del plan')),
                ('activa', models.BooleanField(default=True)),
                ('Tipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_visitas', to='home.tipovisita')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_visitas_evaluador', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_visitas', to='home.datosdemograficos')),
            ],
            options={
                'verbose_name': 'Serie de visitas',
                'verbose_name_plural': 'Series de visitas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='historicalvisita',
            name='serie',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.serievisitas', verbose_name='Serie de visitas'),
        ),
        migrations.AddField(
            model_name='visita',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='home.serievisitas', verbose_name='Serie de visitas'),
        ),
    ]
