# Generated by Django 5.0.6 on 2026-09-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_serie_visitas_programadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserievisitas',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list, help_text='Enteros 0=lun … 6=dom. Usado en personalizado y L-V.', verbose_name='Días de la semana'),
        ),
        migrations.AddField(
            model_name='serievisitas',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list, help_text='Enteros 0=lun … 6=dom. Usado en personalizado y L-V.', verbose_name='Días de la semana'),
        ),
        migrations.AlterField(
            model_name='historicalserievisitas',
            name='frecuencia_cada',
            field=models.PositiveIntegerField(default=1, help_text='Reservado por compatibilidad; la UI usa presets de frecuencia.'),
        ),
        migrations.AlterField(
            model_name='historicalserievisitas',
            name='frecuencia_unidad',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('lv', 'Lunes a viernes'), ('custom', 'Personalizado')], default='semanal', max_length=10),
        ),
        migrations.AlterField(
            model_name='serievisitas',
            name='frecuencia_cada',
            field=models.PositiveIntegerField(default=1, help_text='Reservado por compatibilidad; la UI usa presets de frecuencia.'),
        ),
        migrations.AlterField(
            model_name='serievisitas',
            name='frecuencia_unidad',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('lv', 'Lunes a viernes'), ('custom', 'Personalizado')], default='semanal', max_length=10),
        ),
    ]
