# Generated by Django 3.2.6 on 2025-09-18 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_seguimientoinvervencionesresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoIntervencionesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.IntegerField()),
                ('nombre_sesion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('asistencia', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('participacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Motivado', 'Motivado'), ('Apático', 'Apático'), ('Fatigado', 'Fatigado'), ('Ansioso', 'Ansioso'), ('Otro', 'Otro')], max_length=20, null=True)),
                ('tematica', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('visita_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.visitaexamen')),
            ],
        ),
        migrations.DeleteModel(
            name='SeguimientoInvervencionesResult',
        ),
    ]
