# Generated by Django 3.2.6 on 2025-09-18 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20250918_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientointervencionesresult',
            name='visita_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='home.visitaexamen'),
        ),
    ]
