# Generated by Django 5.0.6 on 2026-09-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_mapear_frecuencia_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalserievisitas',
            name='frecuencia_unidad',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('lv', 'Lunes a viernes'), ('custom', 'Personalizado'), ('fechas', 'Fechas específicas')], default='semanal', max_length=10),
        ),
        migrations.AlterField(
            model_name='serievisitas',
            name='frecuencia_unidad',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('lv', 'Lunes a viernes'), ('custom', 'Personalizado'), ('fechas', 'Fechas específicas')], default='semanal', max_length=10),
        ),
    ]
