# Generated by Django 5.2.3 on 2025-07-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20250311_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerlinResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_cambio', models.CharField(max_length=50)),
                ('ronca', models.CharField(max_length=10)),
                ('tipo_ronquido', models.CharField(max_length=50)),
                ('frecuencia_ronquidos', models.CharField(max_length=50)),
                ('ronquido_molesto', models.CharField(max_length=50)),
                ('apnea_observada', models.CharField(max_length=50)),
                ('fatiga_matutina', models.CharField(max_length=50)),
                ('fatiga_dia', models.CharField(max_length=50)),
                ('somnolencia_conducir', models.CharField(max_length=50)),
                ('presion_alta', models.CharField(max_length=50)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.visitaexamen')),
            ],
        ),
        migrations.CreateModel(
            name='EpworthResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentado_leyendo', models.IntegerField()),
                ('viendo_tv', models.IntegerField()),
                ('sentado_teatro', models.IntegerField()),
                ('pasajero_coche', models.IntegerField()),
                ('tumbado_tarde', models.IntegerField()),
                ('charlando', models.IntegerField()),
                ('despues_comer', models.IntegerField()),
                ('trafico', models.IntegerField()),
                ('puntaje_total', models.IntegerField()),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.visitaexamen')),
            ],
        ),
        migrations.CreateModel(
            name='MEWResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_levantarse', models.CharField(max_length=10)),
                ('hora_acostarse', models.CharField(max_length=10)),
                ('uso_despertador', models.CharField(max_length=50)),
                ('facilidad_levantarse', models.CharField(max_length=50)),
                ('alerta_manana', models.CharField(max_length=50)),
                ('apetito_manana', models.CharField(max_length=50)),
                ('descanso_manana', models.CharField(max_length=50)),
                ('hora_acostarse_libre', models.CharField(max_length=10)),
                ('ejercicio_fisico', models.CharField(max_length=50)),
                ('hora_cansancio_noche', models.CharField(max_length=10)),
                ('horario_prueba_mental', models.CharField(max_length=50)),
                ('nivel_cansancia_11', models.CharField(max_length=50)),
                ('hora_despertarse_si_tarde', models.CharField(max_length=10)),
                ('guardia_nocturna', models.CharField(max_length=50)),
                ('horario_trabajo_fisico', models.CharField(max_length=50)),
                ('ejercicio_nocturno', models.CharField(max_length=50)),
                ('horario_trabajo', models.CharField(max_length=50)),
                ('maximo_bienestar', models.CharField(max_length=50)),
                ('tipo_persona', models.CharField(max_length=50)),
                ('puntuacion', models.IntegerField()),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.visitaexamen')),
            ],
        ),
        migrations.CreateModel(
            name='PittsburghResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_acostarse', models.CharField(max_length=10)),
                ('latencia_sueno', models.IntegerField()),
                ('hora_levantarse', models.CharField(max_length=10)),
                ('horas_dormidas', models.FloatField()),
                ('conciliar_sueno', models.CharField(max_length=100)),
                ('despertarse_sueno', models.CharField(max_length=100)),
                ('levantarse_servicio_sueno', models.CharField(max_length=100)),
                ('respirar', models.CharField(max_length=100)),
                ('toser_roncar_sueno', models.CharField(max_length=100)),
                ('sentir_frio_sueno', models.CharField(max_length=100)),
                ('calor_sueno', models.CharField(max_length=100)),
                ('pesadillas_sueno', models.CharField(max_length=100)),
                ('dolores_sueno', models.CharField(max_length=100)),
                ('otras_razones', models.CharField(blank=True, max_length=100, null=True)),
                ('otras_sueno', models.CharField(blank=True, max_length=100, null=True)),
                ('calidad_sueno', models.CharField(max_length=100)),
                ('medicinas_sueno', models.CharField(max_length=100)),
                ('somnolencia_sueno', models.CharField(max_length=100)),
                ('problemas_animos_sueno', models.CharField(max_length=100)),
                ('duerme_acompanado', models.CharField(max_length=10)),
                ('ronquidos_ruidosos', models.CharField(blank=True, max_length=100, null=True)),
                ('pausas_respiracion', models.CharField(blank=True, max_length=100, null=True)),
                ('sacudidas_piernas', models.CharField(blank=True, max_length=100, null=True)),
                ('desorientacion_confusion', models.CharField(blank=True, max_length=100, null=True)),
                ('otros_inconvenientes', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_inconvenientes', models.CharField(blank=True, max_length=100, null=True)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.visitaexamen')),
            ],
        ),
    ]
