# Generated by Django 3.2.6 on 2025-09-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_seguimientointervencionesresult_visita_examen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguimientointervencionesresult',
            unique_together={('visita_examen', 'numero_sesion')},
        ),
    ]
