# Generated by Django 3.2.6 on 2025-09-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_seguimientointervencionesresult_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidadornpiresult',
            name='interpretacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidadornpiresult',
            name='puntaje_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
