# Generated by Django 5.2.3 on 2025-07-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_berlinresult_epworthresult_mewresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewresult',
            name='hora_acostarse',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='hora_levantarse',
            field=models.CharField(max_length=50),
        ),
    ]
