# Generated by Django 3.2.6 on 2025-09-20 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20250919_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidadornpiresult',
            name='interpretacion',
        ),
    ]
