# Generated by Django 5.2.3 on 2025-07-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_mewresult_hora_acostarse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewresult',
            name='alerta_manana',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='apetito_manana',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='descanso_manana',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='ejercicio_fisico',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='ejercicio_nocturno',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='facilidad_levantarse',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='guardia_nocturna',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='hora_acostarse',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='hora_acostarse_libre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='hora_cansancio_noche',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='hora_despertarse_si_tarde',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='hora_levantarse',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='horario_prueba_mental',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='horario_trabajo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='horario_trabajo_fisico',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='maximo_bienestar',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='nivel_cansancia_11',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='tipo_persona',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mewresult',
            name='uso_despertador',
            field=models.CharField(max_length=150),
        ),
    ]
