# Generated by Django 3.2.6 on 2025-09-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_cuidadornpiresult_interpretacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidadornpiresult',
            name='carga_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
