# Generated by Django 5.2.3 on 2025-07-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_mewresult_alerta_manana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mewresult',
            name='horario_prueba_mental',
        ),
    ]
