# Generated by Django 3.2.6 on 2025-09-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_cuidadornpiresult_carga_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettyferrelresult',
            name='puntaje_total',
            field=models.IntegerField(default=0),
        ),
    ]
