# Generated by Django 3.2.6 on 2025-09-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_bettyferrelresult_puntaje_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('distinct_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('properties', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
