# Generated by Django 5.2.3 on 2025-07-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_suenoanamnesisresult_sintomasueno_sintomadiurnosueno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtenasResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('induccion_dormir', models.CharField(max_length=50)),
                ('despertares_noche', models.CharField(max_length=50)),
                ('despertar_temprano', models.CharField(max_length=50)),
                ('duracion_dormir', models.CharField(max_length=50)),
                ('calidad_dormir', models.CharField(max_length=50)),
                ('bienestar_dia', models.CharField(max_length=50)),
                ('funcionamiento_dia', models.CharField(max_length=50)),
                ('somnolencia_dia', models.CharField(max_length=50)),
                ('puntuacion_total', models.IntegerField(blank=True, null=True)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.visitaexamen')),
            ],
        ),
    ]
