# Generated by Django 3.2.6 on 2025-09-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_interactionmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesVisitaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_revisado', models.BooleanField(default=False)),
                ('fue_actualizado', models.BooleanField(default=False)),
                ('notas_visita', models.TextField(blank=True, null=True, verbose_name='Notas específicas de esta visita')),
                ('fecha_revision', models.DateTimeField(auto_now=True)),
                ('revisado_por', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Enlace Antecedentes-Visita',
                'verbose_name_plural': 'Enlaces Antecedentes-Visitas',
            },
        ),
        migrations.RemoveField(
            model_name='antecedentefamiliar',
            name='antecedente_result',
        ),
        migrations.RemoveField(
            model_name='antecedentefarmacologico',
            name='antecedente_result',
        ),
        migrations.RemoveField(
            model_name='antecedenteginecoobstetrico',
            name='antecedente_result',
        ),
        migrations.RemoveField(
            model_name='antecedentepatologico',
            name='antecedente_result',
        ),
        migrations.RemoveField(
            model_name='antecedentequirurgico',
            name='antecedente_result',
        ),
        migrations.RemoveField(
            model_name='antecedentetoxico',
            name='antecedente_result',
        ),
        migrations.RemoveField(
            model_name='antecedentetraumatico',
            name='antecedente_result',
        ),
        migrations.RemoveField(
            model_name='detallerevisionsistemas',
            name='revision_sistemas_result',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='visita_examen',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='medicamentos_result',
        ),
        migrations.RemoveField(
            model_name='medicamentosresult',
            name='visita_examen',
        ),
        migrations.RemoveField(
            model_name='revisionsistemasresult',
            name='visita_examen',
        ),
        migrations.AlterModelOptions(
            name='antecedentesresult',
            options={'verbose_name': 'Antecedentes Médicos del Paciente', 'verbose_name_plural': 'Antecedentes Médicos de Pacientes'},
        ),
        migrations.RemoveField(
            model_name='antecedentesresult',
            name='visita_examen',
        ),
        migrations.AddField(
            model_name='antecedentesresult',
            name='actualizado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='antecedentesresult',
            name='creado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='antecedentesresult',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='antecedentesresult',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentesresult',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_medicos', to='home.datosdemograficos', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='antecedentesresult',
            name='ultima_visita_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.visitaexamen', verbose_name='Última Visita de Actualización'),
        ),
        migrations.DeleteModel(
            name='AntecedenteAlergico',
        ),
        migrations.DeleteModel(
            name='AntecedenteFamiliar',
        ),
        migrations.DeleteModel(
            name='AntecedenteFarmacologico',
        ),
        migrations.DeleteModel(
            name='AntecedenteGinecoObstetrico',
        ),
        migrations.DeleteModel(
            name='AntecedentePatologico',
        ),
        migrations.DeleteModel(
            name='AntecedenteQuirurgico',
        ),
        migrations.DeleteModel(
            name='AntecedenteToxico',
        ),
        migrations.DeleteModel(
            name='AntecedenteTraumatico',
        ),
        migrations.DeleteModel(
            name='DetalleRevisionSistemas',
        ),
        migrations.DeleteModel(
            name='ExamenNeurologicoResult',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
        migrations.DeleteModel(
            name='MedicamentosResult',
        ),
        migrations.DeleteModel(
            name='RevisionSistemasResult',
        ),
        migrations.AddField(
            model_name='antecedentesvisitalink',
            name='antecedentes_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_links', to='home.antecedentesresult'),
        ),
        migrations.AddField(
            model_name='antecedentesvisitalink',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_link', to='home.visitaexamen'),
        ),
    ]
