# Generated by Django 5.2.3 on 2025-07-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_atenasresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuenoFisicoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(blank=True, null=True)),
                ('talla', models.FloatField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('rango_imc', models.CharField(blank=True, max_length=50, null=True)),
                ('circunferencia_cuello', models.FloatField(blank=True, null=True)),
                ('perimetro_abdominal', models.FloatField(blank=True, null=True)),
                ('simetria_narinas', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_narina', models.CharField(blank=True, max_length=50, null=True)),
                ('desviacion_septo', models.CharField(blank=True, max_length=50, null=True)),
                ('hipertrofia_cornetes', models.CharField(blank=True, max_length=50, null=True)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('hipertrofia_uvula', models.CharField(blank=True, max_length=50, null=True)),
                ('biotipo', models.CharField(blank=True, max_length=50, null=True)),
                ('mallampati', models.CharField(blank=True, max_length=50, null=True)),
                ('amigdalas', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_mordida', models.CharField(blank=True, max_length=50, null=True)),
                ('alteracion_craneo', models.CharField(blank=True, max_length=100, null=True)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.visitaexamen')),
            ],
        ),
    ]
