# Generated by Django 5.2.3 on 2025-07-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_suenofisicoresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad_dormir', models.CharField(max_length=50)),
                ('dificultad_mantener_sueno', models.CharField(max_length=50)),
                ('despertar_temprano', models.CharField(max_length=50)),
                ('satisfaccion_sueno', models.CharField(max_length=50)),
                ('notabilidad_problema', models.CharField(max_length=50)),
                ('preocupacion_sueno', models.CharField(max_length=50)),
                ('interferencia_sueno', models.CharField(max_length=50)),
                ('puntuacion_total', models.IntegerField(blank=True, null=True)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.visitaexamen')),
            ],
        ),
    ]
