# Generated by Django 5.2.3 on 2025-07-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_isiresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopBangResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronca_fuerte', models.BooleanField(default=False)),
                ('cansado_frecuencia', models.BooleanField(default=False)),
                ('deja_respirar', models.BooleanField(default=False)),
                ('presion_arterial', models.BooleanField(default=False)),
                ('imc_alto', models.BooleanField(default=False)),
                ('mayor_50', models.BooleanField(default=False)),
                ('cuello_grande', models.BooleanField(default=False)),
                ('masculino', models.BooleanField(default=False)),
                ('puntaje_total', models.IntegerField(blank=True, null=True)),
                ('riesgo', models.CharField(blank=True, max_length=20, null=True)),
                ('stop_positivos', models.IntegerField(blank=True, null=True)),
                ('bang_positivos', models.IntegerField(blank=True, null=True)),
                ('alto_riesgo_alternativo', models.BooleanField(default=False)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.visitaexamen')),
            ],
        ),
    ]
