# Generated by Django 3.2.6 on 2025-09-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_detallerevisionsistemas_examenneurologicoresult_medicamento_medicamentosresult_revisionsistemasresul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='arcos_movimiento_inferiores',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='arcos_movimiento_superiores',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='asimetrias_inferiores',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='cuello',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='cuero_cabelludo',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='curvatura_cervical',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='curvatura_lumbar',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='curvatura_toracica',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='dolor_abdominal',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='nariz',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_arcos_inf',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_arcos_sup',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_asimetrias',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_cardiorespiratorio',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_cervical',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_fisuras',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_lumbar',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_maculas',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_papulas',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_pared',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_pustulas',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_soplos',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_toracica',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_torax',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='observaciones_vesiculas',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='oidos',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='otros_hallazgos_cabeza_cuello',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='pared_abdominal',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='tipo_ruidos',
        ),
        migrations.RemoveField(
            model_name='examenfisicoresult',
            name='ubicacion_dolor',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='buen_animo',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='felicidad',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='frecuencia_desamparado',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='interpretacion',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='inutil',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='lleno_energia',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='maravilla_vivir',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='otras_personas_mejor',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='preocupacion',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='problemas_memoria',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='puntaje_total',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='quedarse_casa',
        ),
        migrations.RemoveField(
            model_name='participanteyesavageresult',
            name='sin_esperanza',
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='arcos_movimiento_inferiores_anormal',
            field=models.BooleanField(default=False, verbose_name='Arcos Movimiento Inferiores Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='arcos_movimiento_inferiores_normal',
            field=models.BooleanField(default=False, verbose_name='Arcos Movimiento Inferiores Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='arcos_movimiento_superiores_anormal',
            field=models.BooleanField(default=False, verbose_name='Arcos Movimiento Superiores Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='arcos_movimiento_superiores_normal',
            field=models.BooleanField(default=False, verbose_name='Arcos Movimiento Superiores Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='asimetrias_inferiores_anormal',
            field=models.BooleanField(default=False, verbose_name='Asimetrías Inferiores Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='asimetrias_inferiores_normal',
            field=models.BooleanField(default=False, verbose_name='Asimetrías Inferiores Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='asimetrias_superiores_anormal',
            field=models.BooleanField(default=False, verbose_name='Asimetrías Superiores Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='asimetrias_superiores_normal',
            field=models.BooleanField(default=False, verbose_name='Asimetrías Superiores Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='cuello_anormal',
            field=models.BooleanField(default=False, verbose_name='Cuello Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='cuello_normal',
            field=models.BooleanField(default=False, verbose_name='Cuello Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='cuero_cabelludo_anormal',
            field=models.BooleanField(default=False, verbose_name='Cuero Cabelludo Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='cuero_cabelludo_normal',
            field=models.BooleanField(default=False, verbose_name='Cuero Cabelludo Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='curvatura_cervical_anormal',
            field=models.BooleanField(default=False, verbose_name='Curvatura Cervical Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='curvatura_cervical_normal',
            field=models.BooleanField(default=False, verbose_name='Curvatura Cervical Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='curvatura_lumbar_anormal',
            field=models.BooleanField(default=False, verbose_name='Curvatura Lumbar Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='curvatura_lumbar_normal',
            field=models.BooleanField(default=False, verbose_name='Curvatura Lumbar Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='curvatura_toracica_anormal',
            field=models.BooleanField(default=False, verbose_name='Curvatura Torácica Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='curvatura_toracica_normal',
            field=models.BooleanField(default=False, verbose_name='Curvatura Torácica Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='equimosis',
            field=models.BooleanField(default=False, verbose_name='Equímosis'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='escaras',
            field=models.BooleanField(default=False, verbose_name='Escaras'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='masas',
            field=models.BooleanField(default=False, verbose_name='Masas Presentes'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='megalias',
            field=models.BooleanField(default=False, verbose_name='Megalias Presentes'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='nariz_anormal',
            field=models.BooleanField(default=False, verbose_name='Nariz Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='nariz_normal',
            field=models.BooleanField(default=False, verbose_name='Nariz Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='observaciones_forma_torax',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Forma del Tórax'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='observaciones_murmullo_vesicular',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Murmullo Vesicular'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='observaciones_piel_anexos',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Piel y Anexos'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='observaciones_ruidos_cardiacos',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Ruidos Cardíacos'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='observaciones_ruidos_sobreagregados',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Ruidos Sobreagregados'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='oidos_anormal',
            field=models.BooleanField(default=False, verbose_name='Oídos Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='oidos_normal',
            field=models.BooleanField(default=False, verbose_name='Oídos Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='otros_hallazgos_importantes',
            field=models.TextField(blank=True, null=True, verbose_name='Otros Hallazgos Importantes'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='pared_abdominal_anormal',
            field=models.BooleanField(default=False, verbose_name='Pared Abdominal Anormal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='pared_abdominal_normal',
            field=models.BooleanField(default=False, verbose_name='Pared Abdominal Normal'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='petequias',
            field=models.BooleanField(default=False, verbose_name='Petequias'),
        ),
        migrations.AddField(
            model_name='examenfisicoresult',
            name='ulceras',
            field=models.BooleanField(default=False, verbose_name='Úlceras'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='observaciones_abdomen',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Abdomen'),
        ),
        migrations.AlterField(
            model_name='examenfisicoresult',
            name='peristaltismo',
            field=models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='presente', max_length=20, verbose_name='Peristaltismo'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='termica_torax',
            field=models.BooleanField(default=False, verbose_name='Sensibilidad térmica - Tórax alterado'),
        ),
    ]
