# Generated by Django 3.2.6 on 2025-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20250924_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='buen_animo',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='felicidad',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='frecuencia_desamparado',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='interpretacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='inutil',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='lleno_energia',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='maravilla_vivir',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='otras_personas_mejor',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='preocupacion',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='problemas_memoria',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='puntaje_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='quedarse_casa',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='participanteyesavageresult',
            name='sin_esperanza',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
    ]
