# Generated by Django 5.2.6 on 2025-09-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20250925_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdemograficos',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código del Paciente'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
        migrations.AlterField(
            model_name='medicamentosresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
        migrations.AlterField(
            model_name='revisionsistemasresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen'),
        ),
    ]
