# Generated by Django 5.2.6 on 2025-09-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_datosdemograficos_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientointervencionesresult',
            name='visita_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientointervencionesresult_resultado', to='home.visitaexamen'),
        ),
        migrations.CreateModel(
            name='EstadisticasUsuarioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ingresos', models.IntegerField(default=0)),
                ('sesiones_ingresadas', models.IntegerField(default=0)),
                ('sesiones_convertidas', models.IntegerField(default=0)),
                ('sesiones_abandonadas', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('tiempo_promedio', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_mediano', models.CharField(blank=True, max_length=50, null=True)),
                ('total_clicks', models.IntegerField(default=0)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
