# Generated by Django 5.2.6 on 2025-09-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_seguimientointervencionesresult_visita_examen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticasusuarioresult',
            name='visita_examen',
        ),
    ]
