# Generated by Django 5.2.6 on 2025-10-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_estadisticasusuarioresult_visita_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntajecdrresult',
            name='cdr_interpretacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
