# Generated by Django 5.2.6 on 2025-10-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_puntajecdrresult_cdr_interpretacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cuidado_p1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cuidado_p2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cuidado_p3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='cuidado_p4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='habilidad_domestica_dementia_scale',
            field=models.TextField(blank=True, null=True),
        ),
    ]
