# Generated by Django 5.2.6 on 2025-10-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_cdrcuidadorresult_cuidado_p1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='memoria_mes_calificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='memoria_semana_calificacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
