# Generated by Django 3.2.6 on 2025-10-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_cdrparticipanteresult_memoria_mes_calificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenneurologicoresult',
            old_name='agudeza_visual_alterada',
            new_name='agudeza_visual',
        ),
        migrations.RenameField(
            model_name='examenneurologicoresult',
            old_name='gusto_tercio_anterior',
            new_name='gusto_anterior',
        ),
        migrations.RenameField(
            model_name='examenneurologicoresult',
            old_name='mimica_nasal',
            new_name='mimica_elevacion_nasal',
        ),
        migrations.RenameField(
            model_name='examenneurologicoresult',
            old_name='tacto_frente',
            new_name='tacto_frente_globo',
        ),
        migrations.RenameField(
            model_name='examenneurologicoresult',
            old_name='tacto_labio',
            new_name='tacto_labio_inf_menton',
        ),
        migrations.RenameField(
            model_name='examenneurologicoresult',
            old_name='tacto_parpado',
            new_name='tacto_parpado_labio_sup',
        ),
        migrations.RenameField(
            model_name='examenneurologicoresult',
            old_name='posicion_uvula',
            new_name='uvula',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='dolor_brazo_derecho',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='dolor_brazo_izquierdo',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='dolor_pierna_derecha',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='dolor_pierna_izquierda',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='estiloradial_derecho',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='estiloradial_izquierdo',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='observaciones_pares_craneales',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='tactil_brazo_derecho',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='tactil_brazo_izquierdo',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='tactil_pierna_derecha',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='tactil_pierna_izquierda',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='termica_brazo_derecho',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='termica_brazo_izquierdo',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='termica_pierna_derecha',
        ),
        migrations.RemoveField(
            model_name='examenneurologicoresult',
            name='termica_pierna_izquierda',
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='acufenos',
            field=models.BooleanField(default=False, verbose_name='Acúfenos presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='afonia',
            field=models.BooleanField(default=False, verbose_name='Afonía presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='alcohol_derecho',
            field=models.BooleanField(default=False, verbose_name='Alcohol - Fosa nasal derecha'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='alcohol_izquierdo',
            field=models.BooleanField(default=False, verbose_name='Alcohol - Fosa nasal izquierda'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='amaurosis',
            field=models.BooleanField(default=False, verbose_name='Amaurosis presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='antebrazo_extension_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Extensión antebrazo derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='antebrazo_extension_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Extensión antebrazo izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='antebrazo_flexion_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Flexión antebrazo derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='antebrazo_flexion_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Flexión antebrazo izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='atrofia_lingual',
            field=models.BooleanField(default=False, verbose_name='Atrofia lingual presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='balismos',
            field=models.BooleanField(default=False, verbose_name='Balismos presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='bordes',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Bordes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='brazo_abduccion_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Abducción brazo derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='brazo_abduccion_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Abducción brazo izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='brazo_antepulsion_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Antepulsión brazo derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='brazo_antepulsion_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Antepulsión brazo izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='brazo_rotacion_externa_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Rotación externa brazo derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='brazo_rotacion_externa_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Rotación externa brazo izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='brazo_rotacion_interna_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Rotación interna brazo derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='brazo_rotacion_interna_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Rotación interna brazo izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='calambres',
            field=models.BooleanField(default=False, verbose_name='Calambres presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='canela_derecho',
            field=models.BooleanField(default=False, verbose_name='Canela - Fosa nasal derecha'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='canela_izquierdo',
            field=models.BooleanField(default=False, verbose_name='Canela - Fosa nasal izquierda'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='color_disco',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Color del Disco'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='convulsiones',
            field=models.BooleanField(default=False, verbose_name='Convulsiones presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='coordinacion_dedo_nariz',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Coordinación dedo-nariz'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='corea',
            field=models.BooleanField(default=False, verbose_name='Corea presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='cubitopronador_derecho',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo cubitopronador derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='cubitopronador_izquierdo',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo cubitopronador izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='cutaneo_abdominal_derecho',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo cutáneo abdominal derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='cutaneo_abdominal_izquierdo',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo cutáneo abdominal izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='desviaciones_oculares',
            field=models.BooleanField(default=False, verbose_name='Desviaciones oculares presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='discriminacion_dos_puntos',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Discriminación de dos puntos'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='disfagia',
            field=models.BooleanField(default=False, verbose_name='Disfagia presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='disfonia',
            field=models.BooleanField(default=False, verbose_name='Disfonía presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='distonias',
            field=models.BooleanField(default=False, verbose_name='Distonías presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='dolor_abdomen',
            field=models.BooleanField(default=False, verbose_name='Dolor al pinchazo - Abdomen alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='dolor_faringe',
            field=models.BooleanField(default=False, verbose_name='Dolor en faringe presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='dolor_frente_globo',
            field=models.BooleanField(default=False, verbose_name='Dolor - Frente/globo ocular alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='dolor_labio_inf_menton',
            field=models.BooleanField(default=False, verbose_name='Dolor - Labio inferior/mentón alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='dolor_miembros_inferiores',
            field=models.BooleanField(default=False, verbose_name='Dolor al pinchazo - Miembros inferiores alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='dolor_miembros_superiores',
            field=models.BooleanField(default=False, verbose_name='Dolor al pinchazo - Miembros superiores alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='dolor_parpado_labio_sup',
            field=models.BooleanField(default=False, verbose_name='Dolor - Párpado inferior/labio superior alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='elevacion_parpado',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Elevación párpado superior'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='escotomas',
            field=models.BooleanField(default=False, verbose_name='Escotomas presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='espasmos',
            field=models.BooleanField(default=False, verbose_name='Espasmos presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='estilorradial_derecho',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo estilorradial derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='estilorradial_izquierdo',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo estilorradial izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='exudados',
            field=models.BooleanField(default=False, verbose_name='Exudados presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='fasciculaciones',
            field=models.BooleanField(default=False, verbose_name='Fasciculaciones presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='fasciculaciones_linguales',
            field=models.BooleanField(default=False, verbose_name='Fasciculaciones linguales presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='fotopsias',
            field=models.BooleanField(default=False, verbose_name='Fotopsias presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='glabela',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Reflejo glabela'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='gusto_posterior',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Gusto tercio posterior lengua'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='hemorragias',
            field=models.BooleanField(default=False, verbose_name='Hemorragias presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='hipoacusia',
            field=models.BooleanField(default=False, verbose_name='Hipoacusia presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='hoffman',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Reflejo Hoffman'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='mano_extension_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Extensión mano derecha'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='mano_extension_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Extensión mano izquierda'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='mano_flexion_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Flexión mano derecha'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='mano_flexion_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Flexión mano izquierda'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='mano_prension_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Prensión mano derecha'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='mano_prension_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Prensión mano izquierda'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='marcha_ataxica',
            field=models.BooleanField(default=False, verbose_name='Marcha atáxica presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='marcha_espastica',
            field=models.BooleanField(default=False, verbose_name='Marcha espástica presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='marcha_hemiplejica',
            field=models.BooleanField(default=False, verbose_name='Marcha hemipléjica presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='marcha_lineal',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Marcha lineal'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='marcha_miopatica',
            field=models.BooleanField(default=False, verbose_name='Marcha miopática presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='marcha_parkinsoniana',
            field=models.BooleanField(default=False, verbose_name='Marcha parkinsoniana presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='marcha_polineuritica',
            field=models.BooleanField(default=False, verbose_name='Marcha polineurítica presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='marcha_puntillas',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Marcha en puntillas'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='marcha_steppage',
            field=models.BooleanField(default=False, verbose_name='Marcha en steppage presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='mareo',
            field=models.BooleanField(default=False, verbose_name='Mareo presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='marinesco',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Reflejo Marinesco'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='mimica_buccinadores',
            field=models.BooleanField(default=False, verbose_name='Mímica facial - Buccinadores alterada'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='mimica_orbicular_labios',
            field=models.BooleanField(default=False, verbose_name='Mímica facial - Orbicular labios alterada'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='mioclonias',
            field=models.BooleanField(default=False, verbose_name='Mioclonías presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='mirada_conjugada',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Mirada conjugada'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='movimientos_cuello',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Movimientos del cuello'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='movimientos_seguimiento',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Movimientos seguimiento'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='muslo_abduccion_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Abducción muslo derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='muslo_abduccion_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Abducción muslo izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='muslo_aduccion_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Aducción muslo derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='muslo_aduccion_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Aducción muslo izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='muslo_flexion_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Flexión muslo derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='muslo_flexion_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Flexión muslo izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='observaciones_fuerza',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Fuerza Muscular'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='observaciones_ii_par',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones II Par'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='observaciones_marcha',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Marcha'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='observaciones_oculomotores',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Pares Oculomotores'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='observaciones_v_par',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones V Par'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='observaciones_viii_par',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones VIII Par'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='observaciones_xi_par',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones XI Par'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='observaciones_xii_par',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones XII Par'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='oscurecimientos',
            field=models.BooleanField(default=False, verbose_name='Oscurecimientos presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='paladar',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Paladar'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='palmar',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Reflejo palmar'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='palmomentoniano',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Reflejo palmomentoniano'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pie_eversion_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Eversión pie derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pie_eversion_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Eversión pie izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pie_extension_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Extensión pie derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pie_extension_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Extensión pie izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pie_flexion_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Flexión pie derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pie_flexion_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Flexión pie izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pie_inversion_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Inversión pie derecho'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pie_inversion_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Inversión pie izquierdo'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pierna_extension_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Extensión pierna derecha'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pierna_extension_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Extensión pierna izquierda'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pierna_flexion_der',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Flexión pierna derecha'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pierna_flexion_izq',
            field=models.CharField(blank=True, choices=[('0', '0. No contracción'), ('1', '1. Contracción muscular perceptible sin desplazamiento'), ('2', '2. Movimiento activo sin vencer la gravedad (plano horizontal)'), ('3', '3. Movimiento activo que vence la gravedad (plano vertical)'), ('4', '4. Movimiento activo que vence resistencia moderada'), ('5', '5. Movimiento de fuerza normal')], max_length=1, null=True, verbose_name='Flexión pierna izquierda'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='postura',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Postura'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='prension',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Reflejo prensión'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pronacion_supinacion',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Pronación-supinación manos'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='propiocepcion_inferiores',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Propiocepción miembros inferiores'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='propiocepcion_superiores',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Propiocepción miembros superiores'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='pupilas',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Pupilas'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='reconocimiento_objetos',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Reconocimiento de objetos'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='reflejo_fotomotor',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Reflejo Fotomotor'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='romberg',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Romberg'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='sialorrea',
            field=models.BooleanField(default=False, verbose_name='Sialorrea presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='succion',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Reflejo succión'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='tactil_abdomen',
            field=models.BooleanField(default=False, verbose_name='Táctil superficial - Abdomen alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='tactil_miembros_inferiores',
            field=models.BooleanField(default=False, verbose_name='Táctil superficial - Miembros inferiores alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='tactil_miembros_superiores',
            field=models.BooleanField(default=False, verbose_name='Táctil superficial - Miembros superiores alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='talon_rodilla',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Talón-Rodilla'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='temblores',
            field=models.BooleanField(default=False, verbose_name='Temblores presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='temp_frente_globo',
            field=models.BooleanField(default=False, verbose_name='Temperatura - Frente/globo ocular alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='temp_labio_inf_menton',
            field=models.BooleanField(default=False, verbose_name='Temperatura - Labio inferior/mentón alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='temp_parpado_labio_sup',
            field=models.BooleanField(default=False, verbose_name='Temperatura - Párpado inferior/labio superior alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='termica_abdomen',
            field=models.BooleanField(default=False, verbose_name='Sensibilidad térmica - Abdomen alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='termica_miembros_inferiores',
            field=models.BooleanField(default=False, verbose_name='Sensibilidad térmica - Miembros inferiores alterada'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='termica_miembros_superiores',
            field=models.BooleanField(default=False, verbose_name='Sensibilidad térmica - Miembros superiores alterada'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='tics',
            field=models.BooleanField(default=False, verbose_name='Tics presentes'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='tinitus',
            field=models.BooleanField(default=False, verbose_name='Tínitus presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='trofismo_maseteros',
            field=models.BooleanField(default=False, verbose_name='Trofismo - Maseteros alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='trofismo_pterigoideos',
            field=models.BooleanField(default=False, verbose_name='Trofismo - Pterigoideos alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='trofismo_temporales',
            field=models.BooleanField(default=False, verbose_name='Trofismo - Temporales alterado'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='vertigo',
            field=models.BooleanField(default=False, verbose_name='Vértigo presente'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='vibratoria',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Sensibilidad vibratoria'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='vision_colores',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=10, null=True, verbose_name='Visión de Colores'),
        ),
        migrations.AddField(
            model_name='examenneurologicoresult',
            name='voz_nasal',
            field=models.BooleanField(default=False, verbose_name='Voz nasal presente'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='aquiliano_derecho',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo aquiliano derecho'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='aquiliano_izquierdo',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo aquiliano izquierdo'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='bicipital_derecho',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo bicipital derecho'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='bicipital_izquierdo',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo bicipital izquierdo'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='maseteriano_derecho',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo maseteriano derecho'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='maseteriano_izquierdo',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo maseteriano izquierdo'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='rotuliano_derecho',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo rotuliano derecho'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='rotuliano_izquierdo',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo rotuliano izquierdo'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='tricipital_derecho',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo tricipital derecho'),
        ),
        migrations.AlterField(
            model_name='examenneurologicoresult',
            name='tricipital_izquierdo',
            field=models.CharField(blank=True, choices=[('0', '0. Sin respuesta (arreflexia)'), ('1', '1. Respuesta disminuida (hiporreflexia)'), ('2', '2. Respuesta Normal'), ('3', '3. Respuesta Aumentada (hiperreflexia)'), ('4', '4. Respuesta repetida y rítmica que cesa (clonus agotable)'), ('5', '5. Respuesta repetida y rítmica permanente (clonus perm.)')], max_length=1, null=True, verbose_name='Reflejo tricipital izquierdo'),
        ),
    ]
