# Generated by Django 3.2.6 on 2025-11-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_visita_evaluador'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('email_paciente', models.EmailField(max_length=254)),
                ('nombre_paciente', models.CharField(max_length=200)),
                ('telefono_paciente', models.CharField(blank=True, max_length=20)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], default='agendada', max_length=20)),
                ('fecha_agendamiento', models.DateTimeField(auto_now_add=True)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='home.disponibilidadusuario')),
            ],
            options={
                'unique_together': {('disponibilidad', 'fecha_cita')},
            },
        ),
    ]
