# Generated by Django 5.2.8 on 2025-11-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_citamedica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntajecdrresult',
            name='cdr_interpretacion',
        ),
        migrations.CreateModel(
            name='ConsentimientoInfrmadoParticipanteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('investigador', models.CharField(max_length=255)),
                ('version_consentimiento', models.CharField(max_length=50)),
                ('descripcion_proceso', models.TextField(blank=True, null=True)),
                ('preguntas', models.TextField(blank=True, null=True)),
                ('acepta', models.CharField(max_length=10)),
                ('hora_firma', models.TimeField()),
                ('fecha_firma', models.DateField()),
                ('testigo1', models.CharField(blank=True, max_length=255, null=True)),
                ('testigo2', models.CharField(blank=True, max_length=255, null=True)),
                ('copia_entregada', models.CharField(max_length=10)),
                ('hora_finalizacion', models.TimeField()),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resultado', to='home.visitaexamen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ConsentimientoInformadoParticipanteResult',
        ),
    ]
