# Generated by Django 5.2.8 on 2025-11-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_puntajecdrresult_cdr_interpretacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsentimientoInfrmadoParticipanteResult',
            new_name='ConsentimientoInformadoParticipanteResult',
        ),
    ]
