# Generated by Django 5.2.8 on 2025-12-03 15:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_rename_consentimientoinfrmadoparticipanteresult_consentimientoinformadoparticipanteresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitivoAnamnesisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('descripcion_general', models.TextField(blank=True, null=True)),
                ('apariencia_descripcion', models.TextField(blank=True, null=True)),
                ('apariencia_estado', models.CharField(blank=True, choices=[('Adecuada', 'Adecuada'), ('Inadecuada', 'Inadecuada')], max_length=50, null=True)),
                ('actitud_descripcion', models.TextField(blank=True, null=True)),
                ('estado_alerta_descripcion', models.TextField(blank=True, null=True)),
                ('estado_alerta_seleccion', models.CharField(blank=True, choices=[('Alerta', 'Alerta'), ('Somnolencia', 'Somnolencia'), ('Obnubilación', 'Obnubilación'), ('Estupor', 'Estupor'), ('Coma', 'Coma')], max_length=50, null=True)),
                ('orientacion_descripcion', models.TextField(blank=True, null=True)),
                ('orientacion_seleccion', models.CharField(blank=True, choices=[('Desorientación temporal', 'Desorientación temporal'), ('Desorientación espacial', 'Desorientación espacial'), ('Desorientación en persona', 'Desorientación en persona')], max_length=50, null=True)),
                ('atencion_descripcion', models.TextField(blank=True, null=True)),
                ('memoria_descripcion', models.TextField(blank=True, null=True)),
                ('memoria_lopera_vida', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('memoria_lopera_actual', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('memoria_quejas', models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('memoria_edad_inicio', models.IntegerField(blank=True, null=True)),
                ('memoria_progresivas', models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('memoria_cambio_previo', models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('memoria_compromete_basicas', models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('memoria_compromete_complejas', models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('memoria_compromete_cotidiana', models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('lenguaje_descripcion', models.TextField(blank=True, null=True)),
                ('lenguaje_cantidad', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Logorrea', 'Logorrea'), ('Locuacidad', 'Locuacidad'), ('Laconismo', 'Laconismo'), ('Concretismo', 'Concretismo')], max_length=50, null=True)),
                ('lenguaje_fluido', models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('lenguaje_tono', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Altisonante', 'Altisonante'), ('Musitación', 'Musitación'), ('Aprosodia', 'Aprosodia')], max_length=50, null=True)),
                ('lenguaje_articulacion', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Anormal', 'Anormal')], max_length=50, null=True)),
                ('lenguaje_comprension', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Anormal', 'Anormal')], max_length=50, null=True)),
                ('lenguaje_escritura', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Anormal', 'Anormal')], max_length=50, null=True)),
                ('lenguaje_lectura', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Anormal', 'Anormal')], max_length=50, null=True)),
                ('lenguaje_repeticion', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Anormal', 'Anormal')], max_length=50, null=True)),
                ('pensamiento_descripcion', models.TextField(blank=True, null=True)),
                ('pensamiento_forma', models.CharField(blank=True, choices=[('Velocidad', 'Velocidad'), ('Coherencia', 'Coherencia'), ('Lógica', 'Lógica'), ('Organización', 'Organización'), ('Fuga de ideas', 'Fuga de ideas'), ('Ensalada de palabras', 'Ensalada de palabras'), ('Perseverancia', 'Perseverancia'), ('Circunstancialidad', 'Circunstancialidad'), ('Tangencialidad', 'Tangencialidad'), ('Soliloquio', 'Soliloquio')], max_length=100, null=True)),
                ('pensamiento_contenido', models.CharField(blank=True, choices=[('Ideas delirantes', 'Ideas delirantes'), ('Ideas sobrevaloradas', 'Ideas sobrevaloradas'), ('Ideas obsesivas', 'Ideas obsesivas'), ('Ideas fantasiosas', 'Ideas fantasiosas')], max_length=100, null=True)),
                ('pensamiento_juicio', models.CharField(blank=True, choices=[('En construcción', 'En construcción'), ('Conservado', 'Conservado'), ('Distorsionado', 'Distorsionado'), ('Debilitado', 'Debilitado'), ('Nulo', 'Nulo')], max_length=50, null=True)),
                ('pensamiento_introspeccion', models.CharField(blank=True, choices=[('Adecuada', 'Adecuada'), ('Aceptable', 'Aceptable'), ('Pobre', 'Pobre'), ('Precaria', 'Precaria'), ('Nula', 'Nula')], max_length=50, null=True)),
                ('pensamiento_prospeccion', models.CharField(blank=True, choices=[('Conservada', 'Conservada'), ('Grandiosidad', 'Grandiosidad'), ('Delirante', 'Delirante'), ('Desesperanzadora', 'Desesperanzadora'), ('Nula', 'Nula')], max_length=50, null=True)),
                ('sensopercepcion_descripcion', models.TextField(blank=True, null=True)),
                ('sensopercepcion_alteraciones', models.CharField(blank=True, choices=[('Alucinaciones', 'Alucinaciones'), ('Pseudoalucinaciones', 'Pseudoalucinaciones'), ('Alucinosis', 'Alucinosis'), ('Ilusiones', 'Ilusiones'), ('Anomalías en integración', 'Anomalías en integración')], max_length=100, null=True)),
                ('funcion_ejecutiva_descripcion', models.TextField(blank=True, null=True)),
                ('funcion_ejecutiva_comportamientos', models.CharField(blank=True, max_length=200, null=True)),
                ('comportamiento_edad_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('comportamiento_caracteristicas', models.TextField(blank=True, null=True)),
                ('funcion_ejecutiva_sintomas', models.CharField(blank=True, max_length=200, null=True)),
                ('sintomas_edad_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('sintomas_caracteristicas', models.TextField(blank=True, null=True)),
                ('estado_animo_descripcion', models.TextField(blank=True, null=True)),
                ('estado_animo_cualidades', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_animo_expresiones', models.CharField(blank=True, max_length=100, null=True)),
                ('apetito_descripcion', models.TextField(blank=True, null=True)),
                ('apetito_cambios', models.CharField(blank=True, max_length=200, null=True)),
                ('apetito_edad_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('apetito_caracteristicas', models.TextField(blank=True, null=True)),
                ('funcionalidad_descripcion', models.TextField(blank=True, null=True)),
                ('independencia_vida_diaria', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('independencia_actividades_complejas', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('conducta_motora_descripcion', models.TextField(blank=True, null=True)),
                ('trastornos_cuantitativos', models.CharField(blank=True, choices=[('hiperactividad', 'Hiperactividad'), ('inquietud', 'Inquietud'), ('agitacion', 'Agitación'), ('retardo_psicomotor', 'Retardo psicomotor'), ('hipoactividad', 'Hipoactividad')], max_length=100, null=True)),
                ('trastornos_cualitativos', models.CharField(blank=True, choices=[('catatonia', 'Catatonía'), ('estereotipias', 'Estereotipias'), ('manierismos', 'Manierismos'), ('mimica_gestualidad', 'Alteraciones de la mímica y gestualidad'), ('ambitendencia', 'Ambitendencia'), ('perseveracion', 'Perseveración')], max_length=100, null=True)),
                ('visita_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cognitivo_anamnesis_result', to='home.visitaexamen')),
            ],
            options={
                'verbose_name': 'Resultado Examen Cognitivo Anamnesis',
                'verbose_name_plural': 'Resultados Examenes Cognitivo Anamnesis',
                'db_table': 'cognitivo_anamnesis_result',
            },
        ),
        migrations.CreateModel(
            name='AtencionCognitiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Quejas atencionales', 'Quejas atencionales'), ('Alteración atención sostenida', 'Alteración atención sostenida'), ('Alteración atención dividida', 'Alteración atención dividida'), ('Incapacidad para quedarse quieto', 'Incapacidad para quedarse quieto'), ('Dificultad para finalizar una tarea', 'Dificultad para finalizar una tarea'), ('Dificultad para seguir instrucciones', 'Dificultad para seguir instrucciones'), ('Distracción con estímulos irrelevantes', 'Distracción con estímulos irrelevantes')], max_length=100)),
                ('edad_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='home.cognitivoanamnesisresult')),
            ],
            options={
                'db_table': 'atencion_cognitiva',
            },
        ),
        migrations.CreateModel(
            name='ActividadVidaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comer', 'Comer'), ('asearse', 'Asearse'), ('vestirse', 'Vestirse'), ('desplazarse', 'Desplazarse'), ('comunicarse', 'Comunicarse'), ('control_esfinteres', 'Control de esfínteres')], max_length=50)),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_vida_diaria', to='home.cognitivoanamnesisresult')),
            ],
            options={
                'db_table': 'actividad_vida_diaria',
            },
        ),
        migrations.CreateModel(
            name='ActividadCompleja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('telefono', 'Teléfono'), ('compras', 'Compras'), ('cocinar', 'Cocinar'), ('cuidado_hogar', 'Cuidado del hogar'), ('lavar_ropa', 'Lavar ropa'), ('transporte', 'Transporte'), ('medicacion', 'Manejo de medicación'), ('asuntos_economicos', 'Asuntos económicos')], max_length=50)),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_complejas', to='home.cognitivoanamnesisresult')),
            ],
            options={
                'db_table': 'actividad_compleja',
            },
        ),
        migrations.CreateModel(
            name='ActitudCognitiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Colaborador', 'Colaborador'), ('Desinteresado', 'Desinteresado'), ('Hostil', 'Hostil'), ('Intrusivo', 'Intrusivo'), ('Evasivo', 'Evasivo'), ('Seductor', 'Seductor'), ('Suspicaz', 'Suspicaz'), ('Hiperfamiliar', 'Hiperfamiliar'), ('Complaciente', 'Complaciente'), ('Pueril', 'Pueril'), ('Amable', 'Amable'), ('Agresivo', 'Agresivo'), ('Negativista', 'Negativista')], max_length=50)),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actitudes', to='home.cognitivoanamnesisresult')),
            ],
            options={
                'db_table': 'actitud_cognitiva',
            },
        ),
        migrations.CreateModel(
            name='ErrorLenguajeCognitivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Errores sintácticos', 'Errores sintácticos'), ('Errores fonéticos', 'Errores fonéticos'), ('Errores semánticos', 'Errores semánticos')], max_length=50)),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores_lenguaje', to='home.cognitivoanamnesisresult')),
            ],
            options={
                'db_table': 'error_lenguaje_cognitivo',
            },
        ),
    ]
