# Generated by Django 5.2.8 on 2025-12-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_cognitivoanamnesisresult_atencioncognitiva_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actitudcognitiva',
            options={'ordering': ['tipo'], 'verbose_name': 'Actitud Cognitiva', 'verbose_name_plural': 'Actitudes Cognitivas'},
        ),
        migrations.AlterModelOptions(
            name='actividadcompleja',
            options={'ordering': ['tipo'], 'verbose_name': 'Actividad Compleja', 'verbose_name_plural': 'Actividades Complejas'},
        ),
        migrations.AlterModelOptions(
            name='actividadvidadiaria',
            options={'ordering': ['tipo'], 'verbose_name': 'Actividad de Vida Diaria', 'verbose_name_plural': 'Actividades de Vida Diaria'},
        ),
        migrations.AlterModelOptions(
            name='atencioncognitiva',
            options={'ordering': ['tipo'], 'verbose_name': 'Atención Cognitiva', 'verbose_name_plural': 'Atenciones Cognitivas'},
        ),
        migrations.AlterModelOptions(
            name='cognitivoanamnesisresult',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Resultado Examen Cognitivo Anamnesis', 'verbose_name_plural': 'Resultados Exámenes Cognitivo Anamnesis'},
        ),
        migrations.AlterModelOptions(
            name='errorlenguajecognitivo',
            options={'ordering': ['tipo'], 'verbose_name': 'Error Lenguaje Cognitivo', 'verbose_name_plural': 'Errores de Lenguaje Cognitivo'},
        ),
        migrations.AlterModelTable(
            name='actitudcognitiva',
            table=None,
        ),
        migrations.AlterModelTable(
            name='actividadcompleja',
            table=None,
        ),
        migrations.AlterModelTable(
            name='actividadvidadiaria',
            table=None,
        ),
        migrations.AlterModelTable(
            name='atencioncognitiva',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cognitivoanamnesisresult',
            table=None,
        ),
        migrations.AlterModelTable(
            name='errorlenguajecognitivo',
            table=None,
        ),
    ]
