# Generated by Django 5.2.8 on 2025-12-03 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_actitudcognitiva_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cognitivoanamnesisresult',
            name='visita_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cognitivo_anamnesis_resultado', to='home.visitaexamen'),
        ),
    ]
