# Generated by Django 5.2.8 on 2025-12-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_mewresult_cansancio_11pm_mewresult_despertar_tarde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suenoanamnesisresult',
            name='momento_dia_siesta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
