# Generated by Django 5.2.8 on 2025-12-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_suenoanamnesisresult_momento_dia_siesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='conduce_actualmente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='condujo_alguna_vez',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='dificultades_trabajo_memoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='info_suficiente_comunitarias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='juicio_p5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='juicio_p6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_causa_jubilacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='memoria_p8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='nivel_desempeno_domestico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='orientacion_p8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='participa_hogar_geriatrico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='riesgos_conduccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='trabaja_actualmente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='colegio_grado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p7',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cdrparticipanteresult',
            name='orientacion_p8',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
