# Generated by Django 5.2.8 on 2025-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_cdrcuidadorresult_conduce_actualmente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrcuidadorresult',
            name='nivel_desempeno_domestico',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
