# Generated by Django 5.2.8 on 2025-12-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_cdrcuidadorresult_nivel_desempeno_domestico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pittsburghresult',
            name='puntuacion_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
