# Generated by Django 5.2.8 on 2025-12-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_pittsburghresult_puntuacion_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntajecdrresult',
            name='cdr_interpretacion',
            field=models.TextField(blank=True),
        ),
    ]
