# Generated by Django 5.2.8 on 2025-12-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_puntajecdrresult_cdr_interpretacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pittsburghresult',
            name='latencia_sueno',
            field=models.CharField(max_length=100),
        ),
    ]
