# Generated by Django 5.2.8 on 2026-01-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_pittsburghresult_latencia_sueno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdrparticipanteresult',
            name='juicio_p5_correcto',
        ),
        migrations.RemoveField(
            model_name='cdrparticipanteresult',
            name='juicio_p6_correcto',
        ),
        migrations.RemoveField(
            model_name='cdrparticipanteresult',
            name='juicio_p7_correcto',
        ),
        migrations.AddField(
            model_name='cdrparticipanteresult',
            name='juicio_p5',
            field=models.CharField(blank=True, choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], max_length=15, null=True, verbose_name='Juicio pregunta 5'),
        ),
        migrations.AddField(
            model_name='cdrparticipanteresult',
            name='juicio_p6',
            field=models.CharField(blank=True, choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], max_length=15, null=True, verbose_name='Juicio pregunta 6'),
        ),
        migrations.AddField(
            model_name='cdrparticipanteresult',
            name='juicio_p7',
            field=models.CharField(blank=True, choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], max_length=15, null=True, verbose_name='Juicio pregunta 7'),
        ),
    ]
