# Generated by Django 5.2.8 on 2026-01-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_remove_cdrparticipanteresult_juicio_p5_correcto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suenofisicoresult',
            name='frecuencia_cardiaca',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia cardiaca (lpm)'),
        ),
        migrations.AddField(
            model_name='suenofisicoresult',
            name='frecuencia_respiratoria',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria (rpm)'),
        ),
        migrations.AddField(
            model_name='suenofisicoresult',
            name='presion_arterial_diastolica',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Presión diastólica (mmHg)'),
        ),
        migrations.AddField(
            model_name='suenofisicoresult',
            name='presion_arterial_sistolica',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Presión sistólica (mmHg)'),
        ),
        migrations.AddField(
            model_name='suenofisicoresult',
            name='saturacion_oxigeno',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SatO₂ (%)'),
        ),
    ]
