# Generated by Django 5.2.8 on 2026-01-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_suenofisicoresult_frecuencia_cardiaca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='acompanante_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='acompanante_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='acompanante_relacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='acompanante_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado_visita',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20),
        ),
    ]
