# Generated by Django 5.2.8 on 2026-01-20 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_mocaresult_atencion_inversa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoPacienteExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proyecto', models.CharField(max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.datosdemograficos')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.proyecto')),
            ],
            options={
                'unique_together': {('proyecto', 'paciente')},
            },
        ),
    ]
