# Generated by Django 5.2.8 on 2026-01-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_proyectopacienteextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientoinformadocuidadorresult',
            name='firma_cuidador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consentimientoinformadoparticipanteresult',
            name='firma_cuidador',
            field=models.TextField(blank=True, null=True),
        ),
    ]
