# Generated by Django 5.2.8 on 2026-01-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_consentimientoinformadocuidadorresult_firma_cuidador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consentimientoinformadoparticipanteresult',
            old_name='firma_cuidador',
            new_name='firma_participante',
        ),
    ]
