# Generated by Django 5.0.6 on 2026-01-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_rename_firma_cuidador_consentimientoinformadoparticipanteresult_firma_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentimientoinformadoparticipanteresult',
            name='version_consentimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
