# Generated by Django 5.0.6 on 2026-01-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_consentimientoinformadoparticipanteresult_version_consentimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentimientoinformadocuidadorresult',
            name='version_consentimiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consentimientoinformadoparticipanteresult',
            name='version_consentimiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
