# Generated by Django 5.0.6 on 2026-01-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_alter_consentimientoinformadocuidadorresult_version_consentimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antecedentefarmacologico',
            options={'ordering': ['-fecha_inicio', 'nombre_comercial'], 'verbose_name': 'Antecedente Farmacológico', 'verbose_name_plural': 'Antecedentes Farmacológicos'},
        ),
        migrations.RemoveField(
            model_name='antecedentefarmacologico',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='antecedentefarmacologico',
            name='detalle_complicaciones',
        ),
        migrations.RemoveField(
            model_name='antecedentefarmacologico',
            name='detalle_tratamiento',
        ),
        migrations.RemoveField(
            model_name='antecedentefarmacologico',
            name='recibio_tratamiento',
        ),
        migrations.RemoveField(
            model_name='antecedentefarmacologico',
            name='tuvo_complicaciones',
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='adherencia',
            field=models.CharField(choices=[('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala'), ('no_evaluada', 'No Evaluada')], default='no_evaluada', max_length=20, verbose_name='Adherencia al Tratamiento'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='cantidad',
            field=models.CharField(help_text='Ej: 1 tableta, 5 ml, 2 gotas', max_length=100, null=True, verbose_name='Cantidad por Toma'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='concentracion',
            field=models.CharField(help_text='Ej: 500, 25, 10/5', max_length=100, null=True, verbose_name='Concentración'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='descripcion_efectos_adversos',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de Efectos Adversos'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='efectos_adversos',
            field=models.BooleanField(default=False, verbose_name='¿Presenta Efectos Adversos?'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='frecuencia',
            field=models.CharField(help_text='Ej: Cada 8 horas, 2 veces al día, PRN', max_length=100, null=True, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='indicacion',
            field=models.TextField(null=True, verbose_name='Indicación/Motivo del Tratamiento'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='nombre_comercial',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre Comercial'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='nombre_generico',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Genérico (DCI)'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='presentacion',
            field=models.CharField(choices=[('tableta', 'Tableta'), ('capsula', 'Cápsula'), ('solucion', 'Solución'), ('ampolla', 'Ampolla'), ('spray', 'Spray'), ('jarabe', 'Jarabe'), ('crema', 'Crema'), ('pomada', 'Pomada'), ('gel', 'Gel'), ('ovulos', 'Óvulos'), ('supositorio', 'Supositorio'), ('parche', 'Parche'), ('inhalador', 'Inhalador'), ('gotas', 'Gotas'), ('otros', 'Otros')], max_length=50, null=True, verbose_name='Presentación'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='unidad',
            field=models.CharField(choices=[('microgramos', 'Microgramos (μg)'), ('miligramos', 'Miligramos (mg)'), ('gramos', 'Gramos (g)'), ('mililitros', 'Mililitros (ml)'), ('porcentaje', 'Porcentaje (%)'), ('volumen', 'Volumen'), ('unidades_internacionales', 'Unidades Internacionales (UI)'), ('miliequivalentes', 'Miliequivalentes (mEq)'), ('otros', 'Otros')], max_length=50, null=True, verbose_name='Unidad de Concentración'),
        ),
        migrations.AddField(
            model_name='antecedentefarmacologico',
            name='via_administracion',
            field=models.CharField(choices=[('oral', 'Oral'), ('topico', 'Tópico'), ('intramuscular', 'Intramuscular'), ('subcutaneo', 'Subcutáneo'), ('intravenoso', 'Intravenoso'), ('intrarectal', 'Intrarectal'), ('vaginal', 'Vaginal'), ('subdermico', 'Subdérmico'), ('otico', 'Ótico'), ('optico', 'Óptico'), ('intranasal', 'Intranasal'), ('inhalatorio', 'Inhalatorio'), ('transdermico', 'Transdérmico'), ('sublingual', 'Sublingual'), ('otros', 'Otros')], max_length=50, null=True, verbose_name='Vía de Administración'),
        ),
        migrations.AlterField(
            model_name='antecedentefarmacologico',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Medicamento Activo'),
        ),
        migrations.AlterField(
            model_name='antecedentefarmacologico',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, help_text='Dejar vacío si es tratamiento continuo', null=True, verbose_name='Fecha de Finalización'),
        ),
    ]
