# Generated by Django 5.0.6 on 2026-01-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_alter_antecedentefarmacologico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suenoanamnesisresult',
            name='periodo_siestas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
