# Generated by Django 5.0.6 on 2026-01-27 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_customuser_firma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='firmado',
            field=models.BooleanField(default=False, verbose_name='Firmado'),
        ),
        migrations.AddField(
            model_name='visita',
            name='firmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_firmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visita',
            name='evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_evaluador', to=settings.AUTH_USER_MODEL),
        ),
    ]
