# Generated by Django 5.0.6 on 2026-01-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoquejasueno',
            name='evolucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
