# Generated by Django 5.0.6 on 2026-01-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_alter_tipoquejasueno_evolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisgeneralresult',
            name='fecha_proximo_seguimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima fecha de seguimiento'),
        ),
    ]
