# Generated by Django 5.0.6 on 2026-02-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_suenoanamnesisresult_posicion_dormir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='home.proyecto', verbose_name='Proyecto asociado'),
        ),
    ]
