# Generated by Django 5.0.6 on 2026-03-03 03:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_create_default_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDatosDemograficos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('NUIP', 'Número Único de Identificación Personal'), ('CE', 'Cédula de Extranjería'), ('PS', 'Pasaporte')], default='', max_length=50)),
                ('numero_documento', models.CharField(db_index=True, max_length=20)),
                ('celular', models.CharField(db_index=True, default='', max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='', max_length=10)),
                ('municipio_nacimiento', models.CharField(default='', max_length=100)),
                ('departamento_nacimiento', models.CharField(default='', max_length=100)),
                ('pais_nacimiento', models.CharField(default='', max_length=100)),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero(a)'), ('Casado', 'Casado(a)'), ('UnionLibre', 'Unión libre'), ('Viudo', 'Viudo(a)')], default='', max_length=20)),
                ('escolaridad', models.CharField(blank=True, choices=[('primario', 'Primario'), ('bachiller', 'Bachiller'), ('universidad', 'Universidad'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('especializacion', 'Especialización')], max_length=20, null=True, verbose_name='Escolaridad')),
                ('ocupacion', models.CharField(max_length=100)),
                ('lateralidad', models.CharField(choices=[('Diestro', 'Diestro'), ('Zurdo', 'Zurdo'), ('Ambidiestro', 'Ambidiestro')], default='', max_length=20)),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True, verbose_name='Grupo Sanguíneo')),
                ('religion', models.CharField(max_length=100)),
                ('eps', models.CharField(max_length=100)),
                ('regimen', models.CharField(choices=[('Contributivo', 'Contributivo'), ('Subsidiado', 'Subsidiado'), ('Vinculado', 'Vinculado'), ('Otro', 'Otro')], default='', max_length=20)),
                ('direccion', models.CharField(default='', max_length=200)),
                ('municipio_residencia', models.CharField(default='', max_length=100)),
                ('departamento_residencia', models.CharField(default='', max_length=100)),
                ('pais_residencia', models.CharField(default='', max_length=100)),
                ('correo', models.EmailField(db_index=True, default='sincorreo@example.com', max_length=254, verbose_name='Correo Electrónico')),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Código del Paciente')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical datos demograficos',
                'verbose_name_plural': 'historical datos demograficoss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVisita',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Visita')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado_visita', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('firmado', models.BooleanField(default=False, verbose_name='Firmado')),
                ('acompanante_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('acompanante_relacion', models.CharField(blank=True, max_length=100, null=True)),
                ('acompanante_correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('acompanante_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Tipo_visita', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.tipovisita')),
                ('evaluador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('firmado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.datosdemograficos')),
            ],
            options={
                'verbose_name': 'historical visita',
                'verbose_name_plural': 'historical visitas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVisitaExamen',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del Examen')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('notas_examinador', models.TextField(blank=True, null=True, verbose_name='Notas del Examinador')),
                ('evaluador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Evaluador')),
                ('tiempo_duracion', models.DurationField(blank=True, null=True, verbose_name='Tiempo de Duración')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('examen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.examen')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.visita')),
            ],
            options={
                'verbose_name': 'historical Examen de Visita',
                'verbose_name_plural': 'historical Exámenes de Visita',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
