# Generated by Django 5.0.6 on 2026-03-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_add_audit_trail_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisita',
            name='notas_aclaratorias',
            field=models.TextField(blank=True, help_text='Notas de clarificación editables después de la firma.', null=True, verbose_name='Notas aclaratorias'),
        ),
        migrations.AddField(
            model_name='visita',
            name='notas_aclaratorias',
            field=models.TextField(blank=True, help_text='Notas de clarificación editables después de la firma.', null=True, verbose_name='Notas aclaratorias'),
        ),
    ]
